package org.multipaz.testapp

import kotlinx.io.bytestring.ByteString
import org.multipaz.cbor.*
import org.multipaz.cbor.annotation.CborSerializable

// This file was generated by org.multipaz.processor.CodeBuilder, do not edit by hand
@CborSerializable
data class TestData(
	val displayName: String = "",
	val typeDisplayName: String = "",
	val cardArt: ByteString = ByteString(),
) {
	companion object
}

fun TestData.toCbor(): ByteArray {
	return Cbor.encode(toDataItem())
}


fun TestData.Companion.fromCbor(data: ByteArray): TestData {
	return TestData.fromDataItem(Cbor.decode(data))
}

fun TestData.toDataItem(): DataItem {
	val builder = CborMap.builder()
	builder.put("displayName", Tstr(this.displayName))
	builder.put("typeDisplayName", Tstr(this.typeDisplayName))
	builder.put("cardArt", Bstr(this.cardArt.toByteArray()))
	return builder.end().build()
}

fun TestData.Companion.fromDataItem(dataItem: DataItem): TestData {
	val displayName = dataItem["displayName"].asTstr
	val typeDisplayName = dataItem["typeDisplayName"].asTstr
	val cardArt = ByteString(dataItem["cardArt"].asBstr)
	return TestData(
		displayName = displayName,
		typeDisplayName = typeDisplayName,
		cardArt = cardArt,
	)
}
