package net.openid.conformance.statistics;

import java.util.List;

/**
 * Turns the {@code certificationProfileName} list stored on a {@code TEST_PLAN} document
 * into one string, so that cube cells can be grouped, compared and filtered by
 * certification profile without carrying a list around.
 *
 * <p>A plan usually names one profile but may name several (a plan that covers, say, both
 * an OP and a DCR profile), so the key is the names joined with {@value #SEPARATOR}. The
 * stored order is kept: it is generated by the suite from the plan and its variant, so it
 * is the same for every plan configured the same way, and it is also the order an admin
 * sees on the plan itself.
 *
 * <p>The key is what the client sends back as the {@code cert} filter and what it renders
 * in the certification profile list, so it is compared by equality and never re-parsed
 * here; a separator occurring inside a profile name is nevertheless replaced with
 * {@code _}, so that splitting a key always yields as many names as it was built from.
 */
public final class CertKeys {

	/** What the certification profile names of one plan are joined with. */
	public static final String SEPARATOR = " | ";

	private CertKeys() {
	}

	/**
	 * @param certificationProfileName the raw {@code certificationProfileName} field of a
	 *                                 plan document: a list of names, a bare name, or null
	 * @return the canonical key, or the empty string if the plan names no profile
	 */
	public static String canonical(Object certificationProfileName) {
		if (certificationProfileName instanceof CharSequence name) {
			return sanitise(name.toString().trim());
		}
		if (!(certificationProfileName instanceof List<?> names)) {
			// anything else - a missing field, a number, a sub-document - is not a profile
			return "";
		}
		StringBuilder key = new StringBuilder();
		for (Object name : names) {
			if (!(name instanceof CharSequence profile)) {
				continue;
			}
			String sanitised = sanitise(profile.toString().trim());
			if (sanitised.isEmpty()) {
				continue;
			}
			if (key.length() > 0) {
				key.append(SEPARATOR);
			}
			key.append(sanitised);
		}
		return key.toString();
	}

	private static String sanitise(String name) {
		return name.replace(SEPARATOR, "_");
	}
}
