services:
  mongodb:
    image: ${MONGODB_IMAGE:-mongo:6.0.13}
    volumes:
     - ./mongo/data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
  nginx:
    image: registry.gitlab.com/openid/conformance-suite/nginx:${IMAGE_TAG:-latest}
    ports:
     - "8443:8443"
    depends_on:
     - server
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
  server:
    image: registry.gitlab.com/openid/conformance-suite:${IMAGE_TAG:-latest}
    environment:
      BASE_URL: ${BASE_URL:-https://localhost.emobix.co.uk:8443}
      MONGODB_HOST: mongodb
      JAVA_EXTRA_ARGS: "${JAVA_EXTRA_ARGS:---fintechlabs.devmode=true}"
    depends_on:
     - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
