package net.openid.conformance.condition.client;

import net.openid.conformance.condition.Condition.ConditionResult;
import net.openid.conformance.logging.TestInstanceEventLog;
import net.openid.conformance.testmodule.Environment;
import org.apache.commons.io.IOUtils;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.Spy;
import org.mockito.junit.jupiter.MockitoExtension;

import java.nio.charset.StandardCharsets;

import static org.mockito.Mockito.atLeastOnce;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
public class ParseVpTokenAsMdoc_UnitTest {

	@Spy
	private Environment env = new Environment();

	@Mock
	private TestInstanceEventLog eventLog;

	private ParseVpTokenAsMdoc cond;

	/*
	 * @throws java.lang.Exception
	 */
	@BeforeEach
	public void setUp() throws Exception {
		cond = new ParseVpTokenAsMdoc();

		cond.setProperties("UNIT-TEST", eventLog, ConditionResult.INFO);
	}

	@Test
	public void testEvaluate_noError() throws Exception {
		// this was generated by running the VP tests against the OP tests
		String mdocStr = IOUtils.resourceToString("ParseVpTokenAsMdoc/mdoc.txt", StandardCharsets.UTF_8, getClass().getClassLoader());
		mdocStr = mdocStr.replace("\n", "");

		env.putString("vp_token", mdocStr);

		env.putString("config", "client.client_id", "localhost.emobix.co.uk");
		env.putString("response_uri", "https://localhost.emobix.co.uk:8443/test/a/oidf-vp-test-verifier/responseuri");
		env.putString("nonce", "8sigA7tG9GnYfWeRfrAG5PMpHOif-._~");
		env.putString("mdoc_generated_nonce", "Vin3Z2f2d9oAAaq_bOMnYQ");

		cond.execute(env);

		verify(env, atLeastOnce()).getString("vp_token");
	}

	/*
	I don't have the corresponding mdoc generated nonce for this example; need to get a new example with that from Animo
	@Test
	public void testEvaluate_noError2() throws Exception {
		// this was provided by Animo as an mdoc generated by their wallet
		String mdocStr = IOUtils.resourceToString("ParseVpTokenAsMdoc/mdoc-animo.txt", StandardCharsets.UTF_8, getClass().getClassLoader());
		mdocStr = mdocStr.replace("\n", "");

		env.putString("vp_token", mdocStr);

		cond.execute(env);

		verify(env, atLeastOnce()).getString("vp_token");
	}
*/
}
