package net.openid.conformance.condition.client;

import net.openid.conformance.condition.Condition.ConditionResult;
import net.openid.conformance.logging.TestInstanceEventLog;
import net.openid.conformance.testmodule.Environment;
import org.apache.commons.io.IOUtils;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.Spy;
import org.mockito.junit.MockitoJUnitRunner;

import java.nio.charset.StandardCharsets;

import static org.mockito.Mockito.atLeastOnce;
import static org.mockito.Mockito.verify;

@RunWith(MockitoJUnitRunner.class)
public class ParseVpTokenAsMdoc_UnitTest {

	@Spy
	private Environment env = new Environment();

	@Mock
	private TestInstanceEventLog eventLog;

	private ParseVpTokenAsMdoc cond;

	/*
	 * @throws java.lang.Exception
	 */
	@Before
	public void setUp() throws Exception {
		cond = new ParseVpTokenAsMdoc();

		cond.setProperties("UNIT-TEST", eventLog, ConditionResult.INFO);
	}

	@Test
	public void testEvaluate_noError() throws Exception {
		// this was generated by running the VP tests against https://github.com/spruceid/oid4vc-cli-wallet
		String mdocStr = IOUtils.resourceToString("ParseVpTokenAsMdoc/mdoc.txt", StandardCharsets.UTF_8, getClass().getClassLoader());
		mdocStr = mdocStr.replace("\n", "");

		env.putString("vp_token", mdocStr);

		cond.execute(env);

		verify(env, atLeastOnce()).getString("vp_token");
	}

}
