package net.openid.conformance.condition.client;

import com.nimbusds.jose.jwk.gen.ECKeyGenerator;
import net.openid.conformance.condition.Condition;
import net.openid.conformance.logging.BsonEncoding;
import net.openid.conformance.logging.TestInstanceEventLog;
import net.openid.conformance.testmodule.Environment;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.multipaz.documenttype.knowntypes.DrivingLicense;
import org.multipaz.testapp.VciMdocUtils;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

/**
 * Cross-checks the checked-in credential signing material generated by
 * scripts/generate-vp-test-cert.py against the suite's own ISO 18013-5 DS certificate
 * conditions, so drift between the Python generator and the Java checkers fails the build
 * instead of surfacing as warnings at integration-test time. (This test also starts failing
 * when the checked-in certificate expires — the intended alarm to regenerate it.)
 */
@ExtendWith(MockitoExtension.class)
public class VpSigningCertMdocDsProfile_UnitTest {

	private final TestInstanceEventLog eventLog = BsonEncoding.testInstanceEventLog();

	private Environment env;

	@BeforeEach
	public void setUp() throws Exception {
		env = new Environment();
		String signingJwk = Files.readString(Path.of("scripts/certs-keys/vp-mdoc-signing-jwk.json"));
		String deviceKeyJson = new ECKeyGenerator(com.nimbusds.jose.jwk.Curve.P_256).generate().toJSONString();
		String mdocBase64Url = VciMdocUtils.createMdocCredential(
			deviceKeyJson, DrivingLicense.MDL_DOCTYPE, signingJwk);
		MdocCredentialTestUtil.putCredential(env,
			new com.nimbusds.jose.util.Base64URL(mdocBase64Url).decode());
	}

	private <T extends Condition> T conditionOf(T cond) {
		cond.setProperties("UNIT-TEST", eventLog, Condition.ConditionResult.WARNING);
		return cond;
	}

	@Test
	public void scriptGeneratedCertPassesKeyUsageCheck() {
		assertDoesNotThrow(() -> conditionOf(new ValidateMdocDsCertificateKeyUsage()).execute(env));
	}

	@Test
	public void scriptGeneratedCertPassesProfileCheck() {
		assertDoesNotThrow(() -> conditionOf(new ValidateMdocDsCertificateProfile()).execute(env));
	}

	@Test
	public void scriptGeneratedCertChainValidatesAgainstScriptGeneratedCa() throws Exception {
		env.putString("credential_trust_anchor_pem",
			Files.readString(Path.of("scripts/certs-keys/vp-signing-ca.crt")));
		assertDoesNotThrow(() -> conditionOf(new ValidateMdocDsCertificateChain()).execute(env));
	}
}
