/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * Regenerate with:
 *   cd frontend && npm run codegen        (online; needs dev Spring server)
 *   cd frontend && npm run codegen:offline (re-merge from committed cache)
 *
 * Source: frontend/src/api/openapi.json (springdoc snapshot)
 *         frontend/src/api/samples/*.json (captured wire payloads)
 *
 * See frontend/src/api/README.md for the full workflow and read-only invariant.
 */
/* eslint-disable */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a list of existing tokens */
    get: operations["listTokens"];
    put?: never;
    /** Create new token */
    post: operations["createToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create test module instance
     * @description Normally a test plan should be created first. After a test is created, use /api/info/{testid} to wait for the test to be in the WAITING state before trying to interact with the test. Configuration and startup run in a background task: failures there are not returned from this call — they surface as status INTERRUPTED and in the result field via GET /api/info/{id}, with details in the test log.
     */
    post: operations["createTest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get test status, results, and exposed strings */
    get: operations["getTestStatus"];
    put?: never;
    /**
     * Start test by id
     * @description The start happens in a background task: startup failures are not returned from this call — they surface via GET /api/info/{id} and the test log.
     */
    post: operations["startTest"];
    /** Cancel test by Id */
    delete: operations["cancelTest"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/browser/{id}/visit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark front-channel external URL as visited */
    post: operations["visitBrowserUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a list of test plan instances with paging
     * @description Which plans are listed is decided by who is asking: an admin sees every plan, anyone else sees their own, and `public=true` lists the published plans. The optional filters below only narrow that listing - the statistics page drills down with them - so none of them can show a plan that would not have been listed anyway.
     *
     *     In addition to the parameters below, any number of plan level variant filters may be sent as `variant.<parameter>=<value>`, e.g. `variant.fapi_profile=openbanking_brazil&variant.client_auth_type=mtls`; a plan has to match all of them. They cannot be declared individually here because the parameter names are the variant parameters of every test plan the suite publishes.
     */
    get: operations["listTestPlans"];
    put?: never;
    /** Create test plan */
    post: operations["createTestPlan"];
    /**
     * Delete every plan a filtered listing shows, and their tests and logs (admin only)
     * @description Takes exactly the parameters `GET /api/plan` takes and deletes what that listing would show, so the way to see what this will do is to list it first. Deleting millions of documents is far too long for a request, so the work runs in the background: this returns 202 and `GET /api/plan/delete-status` reports progress.
     *
     *     Two kinds of plan are never deleted, whatever is asked for: one a certification package has been downloaded for (`immutable`), and one that has been published, since a link to it may be in circulation. They are left out of the count as well as of the deleting.
     *
     *     Refused unless at least one filter is present - there is no way to ask this to delete everything - and unless `confirm` is the number of plans it is about to delete, so that a listing that has changed since it was looked at stops the request rather than deleting something else.
     */
    delete: operations["bulkDeleteTestPlans"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}/share": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get private link to share test plan
     * @description The returned token can be used directly as 'Authorization: Bearer <token>' on the read-only endpoints GET /api/plan/{id}, GET /api/info/{id}, GET /api/log/{id} and GET /api/currentuser.
     */
    post: operations["shareTestPlan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish a test plan by plan Id */
    post: operations["publishTestPlan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}/makemutable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Make a test plan mutable again (requires administrator privileges) */
    post: operations["makeTestPlanMutable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}/certificationpackage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Prepare certification package for a test plan. Also publishes the plan and marks it as immutable.
     * @description The signed certification of conformance is not part of the package; it is submitted through the certification request form instead. Any other multipart part is ignored. The 200 response carries a Content-Disposition attachment header with the package filename.
     */
    post: operations["prepareCertificationPackage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/delete-cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stop the running bulk plan delete (admin only)
     * @description The job stops at the end of the batch it is in; what it has already deleted stays deleted. Re-running the same request carries on from where it stopped.
     */
    post: operations["cancelBulkPlanDelete"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/{id}/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all the images for a test */
    get: operations["listTestImages"];
    put?: never;
    /** Upload image for a test log */
    post: operations["uploadTestImage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/{id}/images/{placeholder}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload the image to existing log entry */
    post: operations["uploadTestImageToPlaceholder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info/{testId}/share": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get private link to share test information
     * @description The returned token can be used directly as 'Authorization: Bearer <token>' on the read-only endpoints GET /api/plan/{id}, GET /api/info/{id}, GET /api/log/{id} and GET /api/currentuser.
     */
    post: operations["shareTest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info/{id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish a test information */
    post: operations["publishTest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/favorite-plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the favorited test plans of the current user */
    get: operations["listFavoritePlans"];
    put?: never;
    /** Add a test plan to the current user's favorites */
    post: operations["addFavoritePlan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mdoc-iaca-root.pem": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns the certificate used for mdoc signing and verification
     * @description Returns the IACA root certificate used for mdoc signing and verification
     */
    get: operations["mdocIacaRootCert"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jwks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the public keys used to sign exported logs
     * @description The JWKS published at this root /jwks endpoint contains only the keys the suite uses to sign downloaded/exported test logs and certification packages (the .sig files in the export zips) — it plays no part in any test protocol flow. Tests that need a protocol-level JWKS publish their own under the per-test /test/... URLs, and private-link share tokens are signed with a different, unpublished key. No authentication is required.
     */
    get: operations["getJwks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ui/spec_links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get specification links
     * @description Map of specification-reference prefix (as used in log entry 'requirements', e.g. 'OIDCC-') to the base URL of that specification.
     */
    get: operations["getSpecLinks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/statistics/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get suite-wide usage statistics across all users (admin only)
     * @description Served from a snapshot that is recomputed in the background at most every 12 hours, because the underlying aggregations group over the whole test database. While the first snapshot is being computed the response is 202 and the client should poll. The filters and the range are applied to that snapshot when the request is answered, so they are free to change and never trigger a recomputation.
     *
     *     In addition to the parameters below, any number of plan level variant filters may be sent as `variant.<parameter>=<value>`, e.g. `variant.fapi_profile=openbanking_brazil&variant.client_auth_type=mtls`; a cell has to match all of them. They cannot be declared individually here because the parameter names are the variant parameters of every test plan the suite publishes.
     *
     *     `data.modules` covers the trailing 24 months only, is clipped to the range by month whatever the granularity, and honours `family` and `plan` as registry membership - a module belongs to every family that has a plan running it. The `variant.<parameter>` and `cert` filters do not apply to it: a test run records neither in a form the module counts can be keyed by. Its `runs` counts only runs by an identified user, since the section counts people and a run written before authentication completed belongs to nobody, so it does not reconcile exactly with the runs charts.
     *
     *     `data.heatmap` and `data.externalHosts` cover the trailing 24 months, and the summary tiles are windowed too: `inProgress` and `stuck` count runs started since the server came up (a run left RUNNING or WAITING by a restart is not in progress), `totalTests` is the run collection's own document count (an estimate to within a few documents) and `totalUsers` counts users who created a test plan, so somebody who has only ever run standalone tests is not in it. Everything else is all time.
     */
    get: operations["getOverview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/server": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get server information */
    get: operations["getServerInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/{id}/wait-state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Long-poll wait until the test's status is one of the requested states */
    get: operations["waitForTestState"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/running": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get list of running testIDs */
    get: operations["listRunningTestIds"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/browser/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the front-channel external URL state for a given test */
    get: operations["getBrowserStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/available": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the available test modules and their attributes */
    get: operations["listAvailableTestModules"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get test plan information by plan id
     * @description Returns the stored plan document (a reduced public projection when public=true): planName, variant, config, started, owner, description, certificationProfileName, modules, version, summary, publish, immutable. Each modules[] entry additionally carries a 'testSummary' of its test module.
     */
    get: operations["getTestPlan"];
    put?: never;
    post?: never;
    /** Delete a test plan and related configuration. Requires the plan to be mutable. */
    delete: operations["deleteTestPlan"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/info/{planName}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get information for one test plan by name */
    get: operations["getTestPlanInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/filter-options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The families and plan names a listing can be narrowed to
     * @description What `GET /api/plan`'s `family` and `plan` parameters accept, so that they can be offered rather than typed. Plan names include the ones the suite no longer publishes - a listing of old plans is mostly made of those, and they are exactly what somebody clearing a database out is looking for - each marked `retired`.
     *
     *     Deliberately not `/api/plan/available`, which answers the same question but carries every plan's modules, variants and configuration fields with it: 680 KB against this one's few.
     *
     *     Readable on a public request (`?public=true`) as well as by a logged in user: this is the plan registry, the same material `/api/plan/available` already answers with on one, and holds nothing about anybody's data. Pinned by `scripts/run-security-tests.py`.
     */
    get: operations["getPlanFilterOptions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/exporthtml/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export the full results for this plan as both html and json in a zip
     * @description The 200 response carries a Content-Disposition attachment header with filename "<planName>-<variant>-<planId>-<date>.zip".
     */
    get: operations["exportPlanLogsHtml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/export/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export all test logs of plan by plan id
     * @description The 200 response carries a Content-Disposition attachment header with filename "<planName>-<variant>-<planId>-<date>.zip".
     */
    get: operations["exportPlanLogs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/delete-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** How far the running (or last) bulk plan delete has got (admin only) */
    get: operations["getBulkPlanDeleteStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/delete-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * How many plans a bulk delete would remove, without removing any (admin only)
     * @description Takes the same parameters as `DELETE /api/plan` and answers what it would do: how many plans the listing shows, how many of those may be deleted, how many are kept because they are immutable or published, and the number to send back as `confirm`.
     */
    get: operations["previewBulkPlanDelete"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/available": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a list of available test plans and their attributes */
    get: operations["listAvailableTestPlans"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all test logs with paging
     * @description Return all published logs when public data is requested, otherwise all test logs if user is admin, or only the user's test logs
     */
    get: operations["listTestLogs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get test log of given testId
     * @description Returns the raw log entries sorted by time. Every entry has _id, testId, testOwner, src (the logging component, e.g. a condition class name) and time (milliseconds since the epoch); most carry msg, and common further keys include result (SUCCESS/FAILURE/WARNING/INFO/REVIEW), requirements (spec references), blockId, img/upload (screenshots) plus arbitrary condition-specific data. For a test published as 'summary' and requested with public=true, entries are restricted to result, testName, testId, src and time. An unknown test id yields an empty array, not a 404.
     */
    get: operations["getTestLog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/exporthtml/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export test logs as html by test id
     * @description The 200 response carries a Content-Disposition attachment header with filename "test-log-<module>-<variant>-<id>.zip".
     */
    get: operations["exportTestLogHtml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/export/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export test log by test id
     * @description The 200 response carries a Content-Disposition attachment header with filename "test-log-<module>-<variant>-<id>.zip".
     */
    get: operations["exportTestLog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lastconfig": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get last configuration of current user
     * @description The most recently saved configuration document: owner, config, variant, time, and either 'testName' (saved when running a standalone test) or 'planName' (saved when creating a plan).
     */
    get: operations["getLastConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get information of all test module instances
     * @deprecated
     * @description This API has been disabled due to performance concerns. If you have a need for it, please email details of your use case to certification@oidf.org Always returns 400.
     */
    get: operations["listAllTestInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get test information by test id */
    get: operations["getTestInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/currentuser": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user information */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/token/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete existing token by token Id */
    delete: operations["deleteToken"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/favorite-plans/{planName}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a test plan from the current user's favorites */
    delete: operations["removeFavoritePlan"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Identity of the user that owns the resource */
    OwnerId: {
      /** @description Issuer of the owner's login identity */
      iss?: string;
      /** @description Subject of the owner's login identity */
      sub?: string;
    };
    /** @description A newly created API token. This is the only response that ever contains the token value itself — store it; it cannot be retrieved again. */
    TokenCreatedResponse: {
      /** @description Id of the token (for listing and deletion, not for authentication) */
      _id?: string;
      /** @description Owner of the token */
      owner?: components["schemas"]["OwnerId"];
      /** @description Reserved; currently always null */
      info?: unknown;
      /** @description The bearer token value to use in the Authorization header */
      token?: string;
      /**
       * Format: int64
       * @description Expiry time in milliseconds since the epoch, or null for a permanent token
       */
      expires?: number;
    };
    /** @description Result of creating a test module instance */
    TestCreatedResponse: {
      /**
       * @description Test module name
       * @example oidcc-server
       */
      name?: string;
      /**
       * @description Id of the new test instance; used with /api/info/{id}, /api/runner/{id} and /api/log/{id}
       * @example qX3wbqjcv0e6qFz
       */
      id?: string;
      /** @description Base URL of this test instance's endpoints */
      url?: string;
    };
    /** @description Error body */
    ErrorResponse: {
      /** @description Human-readable description of what went wrong */
      error?: string;
    };
    /** @description Front-channel interaction state of a running test */
    BrowserDetail: {
      /** @description Whether the UI should render the URLs as QR codes (wallet tests) */
      show_qr_code?: boolean;
      /** @description URLs the tester (or an automated browser) still needs to visit */
      urls?: string[];
      /** @description As 'urls', each with the HTTP method to use */
      urlsWithMethod?: unknown[];
      /** @description Pending browser-API interactions, each with the request object and its submission URL */
      browserApiRequests?: unknown[];
      /** @description Pending requests for the tester to paste a URI, each with a submission URL and description */
      uriInputRequests?: unknown[];
      /** @description URLs already visited */
      visited?: string[];
      /** @description As 'visited', each with the HTTP method used */
      visitedUrlsWithMethod?: unknown[];
      /** @description State of the automated browser runners processing the URLs */
      runners?: unknown[];
    };
    /** @description Live state of a running test instance. Note this does not include the test's status or result — poll GET /api/info/{id} (or /api/runner/{id}/wait-state) for those. */
    TestStatusResponse: {
      /** @description Test module name */
      name?: string;
      /** @description Id of the test instance */
      id?: string;
      /** @description Name-to-value strings the test exposes to the user (e.g. client_id) */
      exposed?: {
        [key: string]: string;
      };
      /** @description Owner of the test */
      owner?: components["schemas"]["OwnerId"];
      /** @description When the test was created, ISO-8601 */
      created?: string;
      /** @description When the test's status last changed, ISO-8601 */
      updated?: string;
      /** @description Details of the test's final error, or null when there is none */
      error?: unknown;
      /** @description Front-channel interaction state; absent for tests without a browser component */
      browser?: components["schemas"]["BrowserDetail"];
    };
    /** @description One test module within a plan */
    ModuleEntry: {
      /**
       * @description Test module name
       * @example oidcc-server
       */
      testModule?: string;
      /** @description Module-specific variant values, if any (null otherwise) */
      variant?: {
        [key: string]: string;
      };
      /** @description Ids of test instances already run for this module (empty at creation) */
      instances?: string[];
    };
    /** @description Result of creating a test plan instance */
    PlanCreatedResponse: {
      /**
       * @description The plan name that was requested
       * @example oidcc-basic-certification-test-plan
       */
      name?: string;
      /**
       * @description Id of the new test plan instance
       * @example Wt3aZAz6PYLOr
       */
      id?: string;
      /** @description The test modules the plan will run, in order */
      modules?: components["schemas"]["ModuleEntry"][];
    };
    /** @description A private link for sharing read-only access */
    ShareLinkResponse: {
      /** @description Browser URL that logs a guest in via a one-time token */
      link?: string;
      /** @description The JWT on its own, usable as 'Authorization: Bearer <token>' on the read-only endpoints */
      token?: string;
      /** @description Informational notice when the private-link signing key is not persistently configured; empty string otherwise */
      message?: string;
    };
    /** @description Result of a publish request */
    PublishResponse: {
      /** @description Id of the published test or plan */
      id?: string;
      /**
       * @description The publication state that was set
       * @enum {string}
       */
      publish?: "summary" | "everything";
    };
    /** @description Certification package could not be prepared because tests failed or are incomplete, the plan id is unknown, or the plan has no certification profile (it is not part of the certification program). Note: a 422 can also be returned with an empty body when the plan could not be marked immutable. */
    CertificationPackageErrorResponse: {
      /**
       * @description Error code
       * @example failed_or_incomplete_tests
       */
      error?: string;
      /** @description Human-readable description */
      error_description?: string;
      /** @description Name of the plan */
      plan_name?: string;
      /** @description Id of the plan instance */
      test_plan_id?: string;
      /** @description The plan's variant selection, as a string */
      variant?: string;
      /** @description Per-module details of the failing or incomplete tests, keyed by module name; absent for the no_certification_profile error */
      failed_tests?: {
        [key: string]: unknown;
      };
    };
    /** @description The current user's favorited plan names */
    FavoritePlansResponse: {
      /** @description Plan names, in the order they were favorited */
      plans?: string[];
    };
    /** @description An existing API token; the token value itself is never returned after creation */
    TokenSummary: {
      /** @description Id of the token */
      _id?: string;
      /**
       * Format: int64
       * @description Expiry time in milliseconds since the epoch, or null for a permanent token
       */
      expires?: number;
    };
    StatisticsCertProfile: {
      name?: string;
      /** Format: int64 */
      users?: number;
      /** Format: int64 */
      plans?: number;
    };
    StatisticsDimensions: {
      plans?: components["schemas"]["StatisticsPlanDimension"][];
      variants?: {
        [key: string]: components["schemas"]["StatisticsVariantValue"][];
      };
      certProfiles?: components["schemas"]["StatisticsCertProfile"][];
      entities?: components["schemas"]["StatisticsEntity"][];
    };
    StatisticsEntity: {
      entity?: string;
      /** Format: int64 */
      runs?: number;
    };
    StatisticsExternalHost: {
      host?: string;
      /** Format: int64 */
      runs?: number;
      /** Format: int64 */
      users?: number;
      lastSeen?: string;
    };
    StatisticsFamilyTotals: {
      /** Format: int64 */
      runs?: number;
      /** Format: int64 */
      plans?: number;
      /** Format: int64 */
      certified?: number;
    };
    StatisticsLastError: {
      message?: string;
      failedAt?: string;
    };
    StatisticsModule: {
      testName?: string;
      /** Format: int64 */
      runs?: number;
      /** Format: int64 */
      users?: number;
      /** Format: int64 */
      failingUsers?: number;
      /** Format: double */
      failingShare?: number;
    };
    StatisticsModules: {
      rows?: components["schemas"]["StatisticsModule"][];
      byRuns?: string[];
      byFailingUsers?: string[];
    };
    StatisticsOverview: {
      periods?: string[];
      granularity?: string;
      families?: string[];
      syntheticFamilies?: string[];
      resultBuckets?: string[];
      testRunsByFamily?: {
        [key: string]: number[];
      };
      plansByFamily?: {
        [key: string]: number[];
      };
      resultsByFamily?: {
        [key: string]: {
          [key: string]: number[];
        };
      };
      certifiedByFamily?: {
        [key: string]: number[];
      };
      familyTotals?: {
        [key: string]: components["schemas"]["StatisticsFamilyTotals"];
      };
      users?: components["schemas"]["StatisticsUsers"];
      tiles?: components["schemas"]["StatisticsTiles"];
      storage?: components["schemas"]["StatisticsStorage"][];
      dimensions?: components["schemas"]["StatisticsDimensions"];
      heatmap?: number[][];
      modules?: components["schemas"]["StatisticsModules"];
      externalHosts?: components["schemas"]["StatisticsExternalHost"][];
      unresolvedPlans?: components["schemas"]["StatisticsUnresolvedPlan"][];
    };
    StatisticsPlanDimension: {
      planName?: string;
      family?: string;
      /** Format: int64 */
      runs?: number;
      /** Format: int64 */
      plans?: number;
    };
    StatisticsReady: {
      status?: string;
      computedAt?: string;
      /** Format: int64 */
      computeDurationMs?: number;
      refreshing?: boolean;
      lastError?: components["schemas"]["StatisticsLastError"];
      data?: components["schemas"]["StatisticsOverview"];
    };
    StatisticsStorage: {
      collection?: string;
      /** Format: int64 */
      count?: number;
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      storageSize?: number;
      /** Format: int64 */
      totalIndexSize?: number;
    };
    StatisticsTiles: {
      /** Format: int64 */
      totalTests?: number;
      /** Format: int64 */
      totalPlans?: number;
      /** Format: int64 */
      totalUsers?: number;
      /** Format: int64 */
      testsLast24h?: number;
      /** Format: int64 */
      testsLast7d?: number;
      /** Format: int64 */
      testsLast30d?: number;
      /** Format: int64 */
      inProgress?: number;
      /** Format: int64 */
      stuck?: number;
      /** Format: int64 */
      certifiedPlans?: number;
      /** Format: int64 */
      publishedPlans?: number;
    };
    StatisticsUnresolvedPlan: {
      planName?: string;
      /** Format: int64 */
      runs?: number;
    };
    StatisticsUsers: {
      activeByPeriod?: number[];
      newByPeriod?: number[];
    };
    StatisticsVariantValue: {
      value?: string;
      /** Format: int64 */
      users?: number;
      /** Format: int64 */
      plans?: number;
    };
    StatisticsPending: {
      status?: string;
      startedAt?: string;
    };
    StatisticsInvalid: {
      status?: string;
      message?: string;
    };
    StatisticsFailed: {
      status?: string;
      message?: string;
      failedAt?: string;
    };
    /** @description The test reached one of the requested states */
    WaitStateReached: {
      /**
       * @description The status the test is now in
       * @enum {string}
       */
      state?:
        | "NOT_YET_CREATED"
        | "CREATED"
        | "CONFIGURED"
        | "RUNNING"
        | "WAITING"
        | "INTERRUPTED"
        | "FINISHED";
    };
    /** @description The wait timed out before the test reached any of the requested states */
    WaitStateTimeout: {
      /** @description Always true */
      timeout?: boolean;
    };
    /** @description Front-channel URL state for a running test (a subset of the 'browser' object returned by GET /api/runner/{id}) */
    BrowserStatusResponse: {
      /** @description Id of the test instance */
      id?: string;
      /** @description Whether the UI should render the URLs as QR codes (wallet tests) */
      show_qr_code?: boolean;
      /** @description URLs the tester (or an automated browser) still needs to visit */
      urls?: string[];
      /** @description URLs already visited */
      visited?: string[];
      /** @description State of the automated browser runners processing the URLs */
      runners?: unknown[];
    };
    /** @description DataTables-style pagination envelope */
    PaginationResponse: {
      /**
       * Format: int32
       * @description The 'draw' value from the request, echoed back
       */
      draw?: number;
      /**
       * Format: int64
       * @description Synthetic count, not a true total: start + length + 1 when a further page exists, otherwise start plus the number of records returned
       */
      recordsTotal?: number;
      /**
       * Format: int64
       * @description Always the same value as recordsTotal (the suite does not compute a separate filtered count)
       */
      recordsFiltered?: number;
      /** @description The page of records; the item type depends on the endpoint */
      data?: unknown[];
    };
    /** @description Stored information about one test instance. When requested with public=true the same shape is returned minus the 'config' field. */
    TestInfoResponse: {
      /** @description Id of the test instance */
      _id?: string;
      /** @description Id of the test instance (same value as _id) */
      testId?: string;
      /**
       * @description Test module name
       * @example oidcc-server
       */
      testName?: string;
      /** @description Selected variant values (a plain name-to-value object; a bare string for pre-variant legacy tests) */
      variant?: {
        [key: string]: string;
      };
      /**
       * @description When the test was created, ISO-8601
       * @example 2026-08-20T13:45:12.345Z
       */
      started?: string;
      /** @description The test configuration JSON (absent when requested with public=true) */
      config?: unknown;
      /** @description Free-text description from the configuration, or null */
      description?: string;
      /** @description Alias used in the test URLs, or null */
      alias?: string;
      /** @description Owner of the test */
      owner?: components["schemas"]["OwnerId"];
      /** @description Id of the plan this test belongs to, or null for a standalone test */
      planId?: string;
      /**
       * @description Current lifecycle status of the test
       * @enum {string}
       */
      status?:
        | "NOT_YET_CREATED"
        | "CREATED"
        | "CONFIGURED"
        | "RUNNING"
        | "WAITING"
        | "INTERRUPTED"
        | "FINISHED";
      /** @description Conformance suite version that ran the test */
      version?: string;
      /** @description Summary line of the test module */
      summary?: string;
      /**
       * @description Publication state: null, 'summary' or 'everything'
       * @enum {string}
       */
      publish?: "summary" | "everything";
      /**
       * @description Current result of the test, or null if not yet known
       * @enum {string}
       */
      result?: "PASSED" | "FAILED" | "WARNING" | "REVIEW" | "SKIPPED" | "UNKNOWN";
    };
    /** @description The currently authenticated user */
    CurrentUserResponse: {
      /** @description Issuer of the user's login identity */
      iss?: string;
      /** @description Subject of the user's login identity */
      sub?: string;
      /** @description String rendering of the principal map (informational only; use iss/sub) */
      principal?: string;
      /** @description Display name from the login provider */
      displayName?: string;
      /** @description Whether the user has the admin role */
      isAdmin?: boolean;
      /** @description True for a guest logged in via a private share link */
      isGuest?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenSummary"][];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Pass {"permanent": true} for a token that never expires; anything else (including omitting the field) creates a token valid for 24 hours */
    requestBody: {
      content: {
        /**
         * @example {
         *       "permanent": true
         *     }
         */
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Created token successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenCreatedResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description To create a token, you must not be an admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createTest: {
    parameters: {
      query: {
        /** @description Test name, use to identify a specific TestModule */
        test: string;
        /** @description Plan Id */
        plan?: string;
        /**
         * @description Variant selection: a JSON object mapping variant parameter names to values; only allowed when creating a standalone test (not from a plan)
         * @example {
         *       "server_metadata": "discovery",
         *       "client_registration": "dynamic_client"
         *     }
         */
        variant?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The test configuration JSON; required when creating a standalone test, must be omitted when creating from a plan */
    requestBody?: {
      content: {
        /**
         * @example {
         *       "alias": "example",
         *       "server": {
         *         "discoveryUrl": "https://as.example.com/.well-known/openid-configuration"
         *       }
         *     }
         */
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Created test successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestCreatedResponse"];
        };
      };
      /** @description You shouldn't supply a configuration when creating a test from a test plan / You should supply a configuration when creating individual test module */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The plan is immutable, so new tests cannot be created in it (note this condition uses 401) / Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions to create test */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find configuration of plan Id you provided */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description There was a failure in creating the test alias */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Test creation failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getTestStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test that you want to get status */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestStatusResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The test you were trying to retrieve is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  startTest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test that you want to run */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Started test successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestStatusResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The test you were trying to run is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cancelTest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test that you want to cancel */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancelled test successfully; returns the pre-cancellation state (the stop happens in the background) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestStatusResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The test you were trying to cancel is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  visitBrowserUrl: {
    parameters: {
      query: {
        /** @description Url which you want to visit */
        url: string;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Visited url successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The test you were trying to retrieve is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find Browser information */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listTestPlans: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
        /** @description DataTables echo counter; returned unchanged as 'draw' in the response so a client can match responses to requests */
        draw?: number;
        /** @description 0-based index of the first record to return */
        start?: number;
        /** @description Page size; 0 (or unset) means 10, values above 1000 are rejected */
        length?: number;
        /** @description Free-text search term, matched with a MongoDB text search */
        search?: string;
        /**
         * @description Sort specification: a flat comma-separated list of column,direction pairs, e.g. 'started,desc'. Direction is 'asc' unless it is exactly 'desc'.
         * @example started,desc
         */
        order?: string;
        /** @description Only list plans of this spec family, as named on the statistics page. */
        family?: string;
        /** @description Only list plans with this exact plan name. */
        plan?: string;
        /** @description Only list plans certified against this certification profile; a plan matches if any one of its profiles is exactly this. */
        cert?: string;
        /** @description Only list plans belonging to this user, by the `sub` of their account. Has to be sent with `owner_iss`, since a `sub` names an account only within the issuer that minted it. Narrows the listing and can never widen it: anyone but an admin still sees only their own plans, so naming another owner lists nothing. */
        owner?: string;
        /** @description The issuer that minted the `owner` sub, as the account was logged in with. */
        owner_iss?: string;
        /** @description Only list plans a certification package has been downloaded for (`true`), or only those it has not (`false`). Omit for both. */
        immutable?: boolean;
        /** @description Only list plans started at or after this point in time; a date (`YYYY-MM-DD`, covering the whole of that day) or a timestamp with a time zone. */
        from?: string;
        /** @description Only list plans started before this point in time, exclusive, in the same format as `from`, so that the bounds of adjacent periods can be passed straight through. */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully; 'data' contains test plan documents (the public projection when public=true) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginationResponse"];
        };
      };
      /** @description A filter parameter could not be used */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createTestPlan: {
    parameters: {
      query: {
        /** @description Plan name */
        planName: string;
        /**
         * @description Variant selection: a JSON object mapping variant parameter names to values
         * @example {
         *       "server_metadata": "discovery",
         *       "client_registration": "dynamic_client"
         *     }
         */
        variant?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The test configuration JSON; may include 'description', 'alias' and 'publish' fields alongside the server/client configuration */
    requestBody: {
      content: {
        /**
         * @example {
         *       "alias": "example",
         *       "server": {
         *         "discoveryUrl": "https://as.example.com/.well-known/openid-configuration"
         *       }
         *     }
         */
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Created test plan successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanCreatedResponse"];
        };
      };
      /** @description Unknown variant parameter(s), invalid alias, or no applicable test modules for the variant */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions to create test plan */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find test plan for provided plan name */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  bulkDeleteTestPlans: {
    parameters: {
      query?: {
        /** @description Delete at most this many plans, oldest first. Omit to delete all of them. */
        limit?: number;
        /** @description The number of plans this will delete, as a check that it is what was seen */
        confirm?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleting has started; poll /api/plan/delete-status */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description No filter was sent, a parameter could not be used, or `confirm` is not what would be deleted */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You must be an admin to delete plans in bulk */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description A bulk delete is already running */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  shareTestPlan: {
    parameters: {
      query: {
        /**
         * @description Number of days until the link expires
         * @example 30
         */
        exp: string;
      };
      header?: never;
      path: {
        /** @description Id of test plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareLinkResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions to share plan */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find test plan for provided plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  publishTestPlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of the test plan to publish */
        id: string;
      };
      cookie?: never;
    };
    /** @description Object with a 'publish' field: 'summary' or 'everything' */
    requestBody: {
      content: {
        /**
         * @example {
         *       "publish": "summary"
         *     }
         */
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Published test plan successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublishResponse"];
        };
      };
      /** @description 'publish' field is missing or its value is not JsonPrimitive */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 'publish' value is not valid or couldn't find test plan by provided plan Id */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  makeTestPlanMutable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of the test plan to make mutable again */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Made the test plan mutable again successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authorized, or the plan could not be found */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  prepareCertificationPackage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @description Client data in zip format. Only required for RP tests
           */
          clientSideData?: string;
        };
      };
    };
    responses: {
      /** @description Prepared successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": string;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Could not publish plan */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tests failed/incomplete, plan id unknown, or the plan has no certification profile (JSON body), or the plan could not be marked immutable (empty body) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CertificationPackageErrorResponse"];
        };
      };
    };
  };
  cancelBulkPlanDelete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Asked it to stop */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You must be an admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  listTestImages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You must be admin or test owner to list a test's images */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  uploadTestImage: {
    parameters: {
      query?: {
        /** @description Description for image */
        description?: string;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    /** @description The image as a data URI string ('data:image/png;base64,...' or 'data:image/jpeg;base64,...'); at most 500KB decoded and at most 2 images per test */
    requestBody: {
      content: {
        /** @example data:image/png;base64,iVBORw0KGgo... */
        "text/plain": unknown;
        "application/json": string;
      };
    };
    responses: {
      /** @description Uploaded image successfully; returns the new log entry */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Image validation failure */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You must be admin or test owner to upload an image */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  uploadTestImageToPlaceholder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
        /** @description Id of the image placeholder created while the test ran */
        placeholder: string;
      };
      cookie?: never;
    };
    /** @description The image as a data URI string ('data:image/png;base64,...' or 'data:image/jpeg;base64,...'); at most 500KB decoded and at most 2 images per test */
    requestBody: {
      content: {
        /** @example data:image/png;base64,iVBORw0KGgo... */
        "text/plain": unknown;
        "application/json": string;
      };
    };
    responses: {
      /** @description Uploaded image successfully; returns the updated log entry (empty if no matching unfilled placeholder exists) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Image validation failure */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You must be admin or test owner to upload an image */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  shareTest: {
    parameters: {
      query: {
        /**
         * @description Number of days until the link expires
         * @example 30
         */
        exp: string;
      };
      header?: never;
      path: {
        /** @description Id of the test to share */
        testId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareLinkResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not permitted for private-link (guest) users */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find the test (or its plan) for the provided test id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  publishTest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test that you want to publish */
        id: string;
      };
      cookie?: never;
    };
    /** @description Object with a 'publish' field: 'summary' or 'everything' */
    requestBody: {
      content: {
        /**
         * @example {
         *       "publish": "summary"
         *     }
         */
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Published successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublishResponse"];
        };
      };
      /** @description 'publish' field is missing or its value is not JsonPrimitive */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 'publish' value is not valid */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listFavoritePlans: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FavoritePlansResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  addFavoritePlan: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description An object containing the plan name to favorite */
    requestBody: {
      content: {
        /**
         * @example {
         *       "plan": "oidcc-basic-certification-test-plan"
         *     }
         */
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Added successfully (idempotent) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FavoritePlansResponse"];
        };
      };
      /** @description Missing or invalid plan name, or the per-user favorites limit is reached */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  mdocIacaRootCert: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The IACA root certificate */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  getJwks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The JWK Set (public keys only) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getSpecLinks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getOverview: {
    parameters: {
      query?: {
        /** @description Recompute the snapshot even if the current one is still fresh; any existing snapshot keeps being served meanwhile */
        refresh?: boolean;
        /** @description The time buckets to report in. Monthly covers the whole history; weekly covers the trailing 104 weeks and is keyed by the Monday of each ISO week. */
        granularity?: "month" | "week";
        /** @description The first period to report, inclusive; `YYYY-MM` for monthly, `YYYY-MM-DD` for weekly (any day of the week, snapped to its Monday). Defaults to as far back as there is data. */
        from?: string;
        /** @description The last period to report, inclusive, in the same format as `from`. Defaults to today. */
        to?: string;
        /** @description Only count test plans of this spec family, as named in the `families` list of the response. */
        family?: string;
        /** @description Only count this test plan, by name, as listed in `dimensions.plans`. */
        plan?: string;
        /** @description Only count test plans certified for this profile, as listed in `dimensions.certProfiles`; a plan certified for several profiles matches any one of them. */
        cert?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A snapshot is available */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsReady"];
        };
      };
      /** @description The first snapshot is still being computed; retry after the Retry-After interval */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsPending"];
        };
      };
      /** @description A filter or range parameter could not be used */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsInvalid"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You must be an admin to view statistics */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description There is no snapshot to serve and computing one failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsFailed"];
        };
      };
    };
  };
  getServerInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  waitForTestState: {
    parameters: {
      query?: {
        /** @description Comma-separated states to stop on; the call returns once the test's status is one of them */
        states?: string;
        /** @description Wall-clock budget in ms, clamped to [1, 30000] */
        timeoutMs?: number;
      };
      header?: never;
      path: {
        /** @description Id of test to wait on */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Status reached one of the requested states ({"state": ...}), or the timeout fired ({"timeout": true}) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["WaitStateReached"]
            | components["schemas"]["WaitStateTimeout"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The test is unknown or you are not authorized */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listRunningTestIds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getBrowserStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrowserStatusResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The test you were trying to retrieve is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find Browser information */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAvailableTestModules: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getTestPlan: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find test plan for provided plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteTestPlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions to delete test plan */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Could not find a plan with the given id, belonging to the user */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The plan is immutable and cannot be deleted */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getTestPlanInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Plan name, used to identify a specific test plan */
        planName: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find test plan for provided plan name */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getPlanFilterOptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  exportPlanLogsHtml: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": string;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find given plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  exportPlanLogs: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": string;
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find given plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getBulkPlanDeleteStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You must be an admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  previewBulkPlanDelete: {
    parameters: {
      query?: {
        /** @description Delete at most this many plans, oldest first */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description A filter parameter could not be used */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description You must be an admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  listAvailableTestPlans: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listTestLogs: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
        /** @description DataTables echo counter; returned unchanged as 'draw' in the response so a client can match responses to requests */
        draw?: number;
        /** @description 0-based index of the first record to return */
        start?: number;
        /** @description Page size; 0 (or unset) means 10, values above 1000 are rejected */
        length?: number;
        /** @description Free-text search term, matched with a MongoDB text search */
        search?: string;
        /**
         * @description Sort specification: a flat comma-separated list of column,direction pairs, e.g. 'started,desc'. Direction is 'asc' unless it is exactly 'desc'.
         * @example started,desc
         */
        order?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully; note 'data' contains per-test information documents (as GET /api/info/{id}), not log entries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginationResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getTestLog: {
    parameters: {
      query?: {
        /** @description Only return log entries with 'time' greater than this value (milliseconds since the epoch); allows incremental fetching */
        since?: number;
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  exportTestLogHtml: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": string;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find given test Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  exportTestLog: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": string;
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find given test Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLastConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully; an empty JSON object when the user has no saved configuration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAllTestInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Always returned: the API is disabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getTestInfo: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestInfoResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session; anonymous requests are accepted when public=true requests published data */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find test information for provided testId */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of token, use to identify a specific token */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted token successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Couldn't find provided token Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  removeFavoritePlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Name of the test plan to remove from favorites */
        planName: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed successfully (no-op if not favorited) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FavoritePlansResponse"];
        };
      };
      /** @description Missing or invalid bearer token / login session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}

// ─── sample-derived: api-server ────────────────────────────────────────
export interface APIServerSample {
  build_time: Date;
  tag: string;
  version: string;
  external_ip: null;
  revision: string;
}
