/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * Regenerate with:
 *   cd frontend && npm run codegen        (online; needs dev Spring server)
 *   cd frontend && npm run codegen:offline (re-merge from committed cache)
 *
 * Source: frontend/src/api/openapi.json (springdoc snapshot)
 *         frontend/src/api/samples/*.json (captured wire payloads)
 *
 * See frontend/src/api/README.md for the full workflow and read-only invariant.
 */
/* eslint-disable */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a list of existing tokens */
    get: operations["getAllTokens"];
    put?: never;
    /** Create new token */
    post: operations["createToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create test module instance
     * @description Normally a test plan should be created first. After a test is created, use /api/info/{testid} to wait for the test to be in the WAITING state before trying to interact with the test
     */
    post: operations["createTest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get test status, results, and exposed strings */
    get: operations["getTestStatus"];
    put?: never;
    /** Start test by id */
    post: operations["startTest"];
    /** Cancel test by Id */
    delete: operations["cancelTest"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/browser/{id}/visit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark front-channel external URL as visited */
    post: operations["visitBrowserUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a list of test plan instances with paging
     * @description Which plans are listed is decided by who is asking: an admin sees every plan, anyone else sees their own, and `public=true` lists the published plans. The optional filters below only narrow that listing - the statistics page drills down with them - so none of them can show a plan that would not have been listed anyway.
     *
     *     In addition to the parameters below, any number of plan level variant filters may be sent as `variant.<parameter>=<value>`, e.g. `variant.fapi_profile=openbanking_brazil&variant.client_auth_type=mtls`; a plan has to match all of them. They cannot be declared individually here because the parameter names are the variant parameters of every test plan the suite publishes.
     */
    get: operations["getTestPlansForCurrentUser"];
    put?: never;
    /** Create test plan */
    post: operations["createTestPlan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}/share": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get private link to share test plan
     * @description Returns a JSON object with three fields: <code>link</code> (a browser URL that logs a guest in via a one-time token), <code>token</code> (the JWT on its own — usable directly as <code>Authorization: Bearer &lt;token&gt;</code> on the read-only endpoints <code>GET /api/plan/{id}</code>, <code>GET /api/info/{id}</code>, <code>GET /api/log/{id}</code>, <code>GET /api/currentuser</code>), and <code>message</code> (an informational notice when the private-link signing key is not persistently configured).
     */
    post: operations["shareLink"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish a test plan by plan Id */
    post: operations["publishTestPlan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}/makemutable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Make a test plan mutable again (requires administrator privileges) */
    post: operations["makeTestPlanMutable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}/certificationpackage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Prepare certification package for a test plan. Also publishes the plan and marks it as immutable. */
    post: operations["prepareCertificationPackageForTestPlan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/{id}/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all the images for a test */
    get: operations["getAllImages"];
    put?: never;
    /** Upload image for a test log */
    post: operations["uploadImageToNewLogEntry"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/{id}/images/{placeholder}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload the image to existing log entry */
    post: operations["uploadImageToExistingLogEntry"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info/{testId}/share": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get private link to share test information
     * @description Returns a JSON object with three fields: <code>link</code> (a browser URL that logs a guest in via a one-time token), <code>token</code> (the JWT on its own — usable directly as <code>Authorization: Bearer &lt;token&gt;</code> on the read-only endpoints <code>GET /api/plan/{id}</code>, <code>GET /api/info/{id}</code>, <code>GET /api/log/{id}</code>, <code>GET /api/currentuser</code>), and <code>message</code> (an informational notice when the private-link signing key is not persistently configured).
     */
    post: operations["shareLink_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info/{id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish a test information */
    post: operations["publishTestInfo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jwks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getJwkSet"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ui/spec_links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Spec Links */
    get: operations["getSpecLinks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/statistics/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get suite-wide usage statistics across all users (admin only)
     * @description Served from a snapshot that is recomputed in the background at most every 12 hours, because the underlying aggregations group over the whole test database. While the first snapshot is being computed the response is 202 and the client should poll. The filters and the range are applied to that snapshot when the request is answered, so they are free to change and never trigger a recomputation.
     *
     *     In addition to the parameters below, any number of plan level variant filters may be sent as `variant.<parameter>=<value>`, e.g. `variant.fapi_profile=openbanking_brazil&variant.client_auth_type=mtls`; a cell has to match all of them. They cannot be declared individually here because the parameter names are the variant parameters of every test plan the suite publishes.
     *
     *     `data.modules` covers the trailing 24 months only, is clipped to the range by month whatever the granularity, and honours `family` and `plan` as registry membership - a module belongs to every family that has a plan running it. The `variant.<parameter>` and `cert` filters do not apply to it: a test run records neither in a form the module counts can be keyed by. Its `runs` counts only runs by an identified user, since the section counts people and a run written before authentication completed belongs to nobody, so it does not reconcile exactly with the runs charts.
     *
     *     `data.heatmap` and `data.externalHosts` cover the trailing 24 months, and the summary tiles are windowed too: `inProgress` and `stuck` count runs of the last year, `totalTests` is the run collection's own document count (an estimate to within a few documents) and `totalUsers` counts users who created a test plan, so somebody who has only ever run standalone tests is not in it. Everything else is all time.
     */
    get: operations["getOverview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/server": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get server information */
    get: operations["getServerInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/{id}/wait-state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Long-poll wait until the test's status is one of the requested states */
    get: operations["waitForState"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/running": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get list of running testIDs */
    get: operations["getAllRunningTestIds"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/browser/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get front-channel external URLs exposed to the [BrowserControl] for a given test */
    get: operations["getBrowserStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runner/available": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get list of available TestModule names */
    get: operations["getAvailableTests"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get test plan information by plan id */
    get: operations["getTestPlan"];
    put?: never;
    post?: never;
    /** Delete a test plan and related configuration. Requires the plan to be mutable. */
    delete: operations["deleteMutableTestPlan"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/info/{planName}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get information for one test plan by name */
    get: operations["getTestPlanInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/exporthtml/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export the full results for this plan as both html and json in a zip */
    get: operations["exportPlanAsHTML"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/export/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export all test logs of plan by plan id */
    get: operations["exportLogsOfPlan"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan/available": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a list of available test plans and their attributes */
    get: operations["getAvailableTestPlans"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all test logs with paging
     * @description Return all published logs when public data is requested, otherwise all test logs if user is admin, or only the user's test logs
     */
    get: operations["getAllTests"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get test log of given testId */
    get: operations["getLogResults"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/exporthtml/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export test logs as html by test id */
    get: operations["exportTestHtml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/log/export/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export test log by test id */
    get: operations["export"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lastconfig": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get last configuration of current user */
    get: operations["getLastConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get information of all test module instances
     * @description Will return all run test modules if user is admin role, otherwise only the logged in user's tests will be returned. This API is currently disabled due to performance concerns. If you have a need for it, please email details of your use case to certification@oidf.org
     */
    get: operations["getAllTests_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get test information by test id */
    get: operations["getTestInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/currentuser": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user information */
    get: operations["getCurrentUserInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/token/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete existing token by token Id */
    delete: operations["deleteToken"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    JsonArray: {
      empty?: boolean;
      /** Format: double */
      asDouble?: number;
      /** Format: int32 */
      asInt?: number;
      /** Format: int64 */
      asLong?: number;
      asBoolean?: boolean;
      /** Format: float */
      asFloat?: number;
      asNumber?: number;
      /** Format: byte */
      asByte?: string;
      /** @deprecated */
      asCharacter?: string;
      asBigDecimal?: number;
      asBigInteger?: number;
      /** Format: int32 */
      asShort?: number;
      asString?: string;
      asJsonObject?: unknown;
      jsonArray?: boolean;
      jsonObject?: boolean;
      jsonPrimitive?: boolean;
      jsonNull?: boolean;
      asJsonArray?: unknown;
      asJsonPrimitive?: components["schemas"]["JsonPrimitive"];
      asJsonNull?: components["schemas"]["JsonNull"];
    };
    JsonNull: {
      /** Format: double */
      asDouble?: number;
      /** Format: int32 */
      asInt?: number;
      /** Format: int64 */
      asLong?: number;
      asBoolean?: boolean;
      asJsonObject?: unknown;
      jsonArray?: boolean;
      jsonObject?: boolean;
      jsonPrimitive?: boolean;
      jsonNull?: boolean;
      asJsonArray?: unknown;
      asJsonPrimitive?: unknown;
      /** Format: float */
      asFloat?: number;
      asJsonNull?: unknown;
      asNumber?: number;
      /** Format: byte */
      asByte?: string;
      /** @deprecated */
      asCharacter?: string;
      asBigDecimal?: number;
      asBigInteger?: number;
      /** Format: int32 */
      asShort?: number;
      asString?: string;
    };
    /** @description Configuration Json */
    JsonObject: {
      empty?: boolean;
      /** Format: double */
      asDouble?: number;
      /** Format: int32 */
      asInt?: number;
      /** Format: int64 */
      asLong?: number;
      asBoolean?: boolean;
      asJsonObject?: components["schemas"]["JsonObject"];
      jsonArray?: boolean;
      jsonObject?: boolean;
      jsonPrimitive?: boolean;
      jsonNull?: boolean;
      asJsonArray?: components["schemas"]["JsonArray"];
      asJsonPrimitive?: components["schemas"]["JsonPrimitive"];
      /** Format: float */
      asFloat?: number;
      asJsonNull?: components["schemas"]["JsonNull"];
      asNumber?: number;
      /** Format: byte */
      asByte?: string;
      /** @deprecated */
      asCharacter?: string;
      asBigDecimal?: number;
      asBigInteger?: number;
      /** Format: int32 */
      asShort?: number;
      asString?: string;
    };
    JsonPrimitive: {
      /** Format: double */
      asDouble?: number;
      /** Format: int32 */
      asInt?: number;
      /** Format: int64 */
      asLong?: number;
      asBoolean?: boolean;
      boolean?: boolean;
      string?: boolean;
      number?: boolean;
      /** Format: float */
      asFloat?: number;
      asNumber?: number;
      /** Format: byte */
      asByte?: string;
      /** @deprecated */
      asCharacter?: string;
      asBigDecimal?: number;
      asBigInteger?: number;
      /** Format: int32 */
      asShort?: number;
      asString?: string;
      asJsonObject?: unknown;
      jsonArray?: boolean;
      jsonObject?: boolean;
      jsonPrimitive?: boolean;
      jsonNull?: boolean;
      asJsonArray?: unknown;
      asJsonPrimitive?: unknown;
      asJsonNull?: components["schemas"]["JsonNull"];
    };
    StreamingResponseBody: unknown;
    StatisticsCertProfile: {
      name?: string;
      /** Format: int64 */
      users?: number;
      /** Format: int64 */
      plans?: number;
    };
    StatisticsDimensions: {
      plans?: components["schemas"]["StatisticsPlanDimension"][];
      variants?: {
        [key: string]: components["schemas"]["StatisticsVariantValue"][];
      };
      certProfiles?: components["schemas"]["StatisticsCertProfile"][];
      entities?: components["schemas"]["StatisticsEntity"][];
    };
    StatisticsEntity: {
      entity?: string;
      /** Format: int64 */
      runs?: number;
    };
    StatisticsExternalHost: {
      host?: string;
      /** Format: int64 */
      runs?: number;
      /** Format: int64 */
      users?: number;
      lastSeen?: string;
    };
    StatisticsLastError: {
      message?: string;
      failedAt?: string;
    };
    StatisticsModule: {
      testName?: string;
      /** Format: int64 */
      runs?: number;
      /** Format: int64 */
      users?: number;
      /** Format: int64 */
      failingUsers?: number;
      /** Format: double */
      failingShare?: number;
    };
    StatisticsOverview: {
      periods?: string[];
      granularity?: string;
      families?: string[];
      resultBuckets?: string[];
      testRunsByFamily?: {
        [key: string]: number[];
      };
      plansByFamily?: {
        [key: string]: number[];
      };
      resultsByFamily?: {
        [key: string]: {
          [key: string]: number[];
        };
      };
      certifiedByFamily?: {
        [key: string]: number[];
      };
      users?: components["schemas"]["StatisticsUsers"];
      tiles?: components["schemas"]["StatisticsTiles"];
      storage?: components["schemas"]["StatisticsStorage"][];
      dimensions?: components["schemas"]["StatisticsDimensions"];
      heatmap?: number[][];
      modules?: components["schemas"]["StatisticsModule"][];
      externalHosts?: components["schemas"]["StatisticsExternalHost"][];
      unresolvedPlans?: components["schemas"]["StatisticsUnresolvedPlan"][];
    };
    StatisticsPlanDimension: {
      planName?: string;
      family?: string;
      /** Format: int64 */
      runs?: number;
      /** Format: int64 */
      plans?: number;
    };
    StatisticsReady: {
      status?: string;
      computedAt?: string;
      /** Format: int64 */
      computeDurationMs?: number;
      refreshing?: boolean;
      lastError?: components["schemas"]["StatisticsLastError"];
      data?: components["schemas"]["StatisticsOverview"];
    };
    StatisticsStorage: {
      collection?: string;
      /** Format: int64 */
      count?: number;
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      storageSize?: number;
      /** Format: int64 */
      totalIndexSize?: number;
    };
    StatisticsTiles: {
      /** Format: int64 */
      totalTests?: number;
      /** Format: int64 */
      totalPlans?: number;
      /** Format: int64 */
      totalUsers?: number;
      /** Format: int64 */
      testsLast24h?: number;
      /** Format: int64 */
      testsLast7d?: number;
      /** Format: int64 */
      testsLast30d?: number;
      /** Format: int64 */
      inProgress?: number;
      /** Format: int64 */
      stuck?: number;
      /** Format: int64 */
      certifiedPlans?: number;
      /** Format: int64 */
      publishedPlans?: number;
    };
    StatisticsUnresolvedPlan: {
      planName?: string;
      /** Format: int64 */
      runs?: number;
    };
    StatisticsUsers: {
      activeByPeriod?: number[];
      newByPeriod?: number[];
    };
    StatisticsVariantValue: {
      value?: string;
      /** Format: int64 */
      users?: number;
      /** Format: int64 */
      plans?: number;
    };
    StatisticsPending: {
      status?: string;
      startedAt?: string;
    };
    StatisticsInvalid: {
      status?: string;
      message?: string;
    };
    StatisticsFailed: {
      status?: string;
      message?: string;
      failedAt?: string;
    };
    PaginationRequest: {
      /** Format: int32 */
      draw?: number;
      /** Format: int32 */
      start?: number;
      /** Format: int32 */
      length?: number;
      search?: string;
      order?: string;
    };
    Document: {
      empty?: boolean;
    } & {
      [key: string]: unknown;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAllTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  createToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JsonObject"];
      };
    };
    responses: {
      /** @description Created token successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description To create a token, you must not be an admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  createTest: {
    parameters: {
      query: {
        /** @description Test name, use to identify a specific TestModule */
        test: string;
        /** @description Plan Id */
        plan?: string;
        /** @description Kind of test variation */
        variant?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["JsonObject"];
      };
    };
    responses: {
      /** @description Created test successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description You shouldn't supply a configuration when creating a test from a test plan / You should supply a configuration when creating individual test module */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Insufficient permissions to create test */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Couldn't find configuration of plan Id you provided */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description There was a failure in creating the test alias */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Created test failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  getTestStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test that you want to get status */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description The test you were trying to retrieve is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  startTest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test that you want to run */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Started test successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description The test you were trying to run is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  cancelTest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test that you want to cancel */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancelled test successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description The test you were trying to cancel is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  visitBrowserUrl: {
    parameters: {
      query: {
        /** @description Url which you want to visit */
        url: string;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Visited url successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string;
        };
      };
      /** @description The test you were trying to retrieve is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string;
        };
      };
      /** @description Couldn't find Browser information */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string;
        };
      };
    };
  };
  getTestPlansForCurrentUser: {
    parameters: {
      query: {
        /** @description Published data only */
        public?: boolean;
        page: components["schemas"]["PaginationRequest"];
        /** @description Only list plans of this spec family, as named on the statistics page. */
        family?: string;
        /** @description Only list plans with this exact plan name. */
        plan?: string;
        /** @description Only list plans certified against this certification profile; a plan matches if any one of its profiles is exactly this. */
        cert?: string;
        /** @description Only list plans started at or after this point in time; a date (`YYYY-MM-DD`, covering the whole of that day) or a timestamp with a time zone. */
        from?: string;
        /** @description Only list plans started before this point in time, exclusive, in the same format as `from`, so that the bounds of adjacent periods can be passed straight through. */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description A filter parameter could not be used */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  createTestPlan: {
    parameters: {
      query: {
        /** @description Plan name */
        planName: string;
        /** @description Kind of test variation */
        variant?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JsonObject"];
      };
    };
    responses: {
      /** @description Created test plan successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Unknown variant parameter(s) for the plan */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Insufficient permissions to create test plan */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Couldn't find test plan for provided plan name */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  shareLink: {
    parameters: {
      query: {
        /** @description Link expiry days */
        exp: string;
      };
      header?: never;
      path: {
        /** @description Id of test plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Insufficient permissions to share plan */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Couldn't find test plan for provided plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  publishTestPlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test plan that you want publish */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JsonObject"];
      };
    };
    responses: {
      /** @description Published test plan successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description 'publish' field is missing or its value is not JsonPrimitive */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description 'publish' value is not valid or couldn't find test plan by provided plan Id */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  makeTestPlanMutable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test plan that you want make mutable again */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Made the test plan mutable again successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": Record<string, never>;
        };
      };
      /** @description Could not find plan */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": Record<string, never>;
        };
      };
      /** @description Not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": Record<string, never>;
        };
      };
    };
  };
  prepareCertificationPackageForTestPlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @description Client data in zip format. Only required for RP tests
           */
          clientSideData?: string;
        };
      };
    };
    responses: {
      /** @description Prepared successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Could not publish plan */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Could not find a plan with the given id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Could not mark the plan as immutable */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
    };
  };
  getAllImages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description In order to upload an image, You must be admin or test owner */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  uploadImageToNewLogEntry: {
    parameters: {
      query?: {
        /** @description Description for image */
        description?: string;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description Uploaded image successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Image validation failure */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description In order to upload an image, You must be admin or test owner */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  uploadImageToExistingLogEntry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
        /** @description Placeholder which created when the test run */
        placeholder: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description Uploaded image successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Image validation failure */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description In order to upload an image, You must be admin or test owner */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  shareLink_1: {
    parameters: {
      query: {
        /** @description Link expiry days */
        exp: string;
      };
      header?: never;
      path: {
        /** @description Id of test that you want to publish */
        testId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Couldn't find test plan for provided plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  publishTestInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test that you want to publish */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JsonObject"];
      };
    };
    responses: {
      /** @description Published successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description 'publish' field is missing or its value is not JsonPrimitive */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description 'publish' value is not valid */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getJwkSet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getSpecLinks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  getOverview: {
    parameters: {
      query?: {
        /** @description Recompute the snapshot even if the current one is still fresh; any existing snapshot keeps being served meanwhile */
        refresh?: boolean;
        /** @description The time buckets to report in. Monthly covers the whole history; weekly covers the trailing 104 weeks and is keyed by the Monday of each ISO week. */
        granularity?: "month" | "week";
        /** @description The first period to report, inclusive; `YYYY-MM` for monthly, `YYYY-MM-DD` for weekly (any day of the week, snapped to its Monday). Defaults to as far back as there is data. */
        from?: string;
        /** @description The last period to report, inclusive, in the same format as `from`. Defaults to today. */
        to?: string;
        /** @description Only count test plans of this spec family, as named in the `families` list of the response. */
        family?: string;
        /** @description Only count this test plan, by name, as listed in `dimensions.plans`. */
        plan?: string;
        /** @description Only count test plans whose certification profiles are exactly this, as listed in `dimensions.certProfiles`; several profiles are joined with ' | '. */
        cert?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A snapshot is available */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsReady"];
        };
      };
      /** @description The first snapshot is still being computed; retry after the Retry-After interval */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsPending"];
        };
      };
      /** @description A filter or range parameter could not be used */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsInvalid"];
        };
      };
      /** @description You must be an admin to view statistics */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description There is no snapshot to serve and computing one failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsFailed"];
        };
      };
    };
  };
  getServerInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  waitForState: {
    parameters: {
      query?: {
        /** @description Comma-separated states to stop on; the call returns once the test's status is one of them */
        states?: string;
        /** @description Wall-clock budget in ms, clamped to [1, 30000] */
        timeoutMs?: number;
      };
      header?: never;
      path: {
        /** @description Id of test to wait on */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Status reached one of the requested states, or timeout fired */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description The test is unknown or you are not authorized */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  getAllRunningTestIds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  getBrowserStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description The test you were trying to retrieve is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Couldn't find Browser information */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  getAvailableTests: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getTestPlan: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Couldn't find test plan for provided plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  deleteMutableTestPlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of test plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Insufficient permissions to delete test plan */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Could not find a plan with the given id, belonging to the user */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description The plan is immutable and cannot be deleted */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StreamingResponseBody"];
        };
      };
    };
  };
  getTestPlanInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Plan name, use to identify a specific TestPlan */
        planName: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Couldn't find test plan for provided plan name */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  exportPlanAsHTML: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Couldn't find given plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
    };
  };
  exportLogsOfPlan: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of plan */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Couldn't find given plan Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
    };
  };
  getAvailableTestPlans: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  getAllTests: {
    parameters: {
      query: {
        /** @description Published data only */
        public?: boolean;
        page: components["schemas"]["PaginationRequest"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getLogResults: {
    parameters: {
      query?: {
        /** @description Since when test created */
        since?: number;
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Document"][];
        };
      };
    };
  };
  exportTestHtml: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Couldn't find given test Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
    };
  };
  export: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** @description Couldn't find given test Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
    };
  };
  getLastConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getAllTests_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getTestInfo: {
    parameters: {
      query?: {
        /** @description Published data only */
        public?: boolean;
      };
      header?: never;
      path: {
        /** @description Id of test */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Couldn't find test information for provided testId */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getCurrentUserInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  deleteToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of token, use to identify a specific token */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted token successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Couldn't find provided token Id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
}

// ─── sample-derived: api-server ────────────────────────────────────────
export interface APIServerSample {
  build_time: Date;
  tag: string;
  version: string;
  external_ip: null;
  revision: string;
}
