package io.fintechlabs.testframework.fapi;

import io.fintechlabs.testframework.openbanking.FAPIRWID2OBDiscoveryEndpointVerification;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationCodeIsBoundToClientIsBoundToClientWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationCodeIsBoundToClientWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationRequestWithoutRequestObjectFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationRequestWithoutRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureClientAssertionInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureClientIdInTokenEndpointWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureClientIdInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureDifferentNonceInsideAndOutsideRequestObjectWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureDifferentNonceInsideAndOutsideRequestObjectWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureExpiredRequestObjectFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureExpiredRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureMTLSHolderOfKeyRequiredWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureMTLSHolderOfKeyRequiredWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureMatchingKeyInAuthorizationRequestWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureMatchingKeyInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRedirectUriInAuthorizationRequestWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRedirectUriInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRegisteredRedirectUriWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRegisteredRedirectUriWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectSignatureAlgorithmIsNotNoneWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectSignatureAlgorithmIsNotNoneWithPrivateKeyAndMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithBadAudFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithBadAudFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithMultipleAudSucceedsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithMultipleAudSucceedsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutExpFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutExpFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutNonceFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutNonceFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutRedirectUriFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutRedirectUriFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutScopeFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutScopeFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutStateWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutStateWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureResponseModeQueryWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureResponseModeQueryWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureResponseTypeCodeFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureResponseTypeCodeFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureServerHandlesNonMatchingIntentIdWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureServerHandlesNonMatchingIntentIdWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureSignedClientAssertionWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureSignedRequestObjectWithRS256FailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureSignedRequestObjectWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBUserRejectsAuthenticationWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBUserRejectsAuthenticationWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.plan.PublishTestPlan;
import io.fintechlabs.testframework.plan.TestPlan;

@PublishTestPlan (
	testPlanName = "fapi-rw-id2-test-plan-v3.0.7",
	displayName = "FAPI-RW-ID2: Authorization server test (V3.0.7; allowable for certification until 24th August)",
	profile = "FAPI-RW-ID2-OpenID-Provider-Authorization-Server-Test",
	testModules = {
		// Normal well behaved client cases
		FAPIRWID2DiscoveryEndpointVerification.class,
		FAPIRWID2.class,
		FAPIRWID2UserRejectsAuthentication.class,
		FAPIRWID2EnsureServerAcceptsRequestObjectWithMultipleAud.class,
		FAPIRWID2OBDiscoveryEndpointVerification.class,
		FAPIRWID2OBWithMTLS.class,
		FAPIRWID2OBUserRejectsAuthenticationWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithMultipleAudSucceedsWithMTLS.class,
		FAPIRWID2OBWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBUserRejectsAuthenticationWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithMultipleAudSucceedsWithPrivateKeyAndMTLSHolderOfKey.class,

		// Possible failure case
		FAPIRWID2EnsureResponseModeQuery.class,
		FAPIRWID2EnsureDifferentNonceInsideAndOutsideRequestObject.class,
		FAPIRWID2EnsureRegisteredRedirectUri.class,
		FAPIRWID2OBEnsureResponseModeQueryWithMTLS.class,
		FAPIRWID2OBEnsureDifferentNonceInsideAndOutsideRequestObjectWithMTLS.class,
		FAPIRWID2OBEnsureRegisteredRedirectUriWithMTLS.class,
		FAPIRWID2OBEnsureResponseModeQueryWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureDifferentNonceInsideAndOutsideRequestObjectWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRegisteredRedirectUriWithPrivateKeyAndMTLSHolderOfKey.class,

		// Negative tests for request objects
		FAPIRWID2EnsureRequestObjectWithoutExpFails.class,
		FAPIRWID2EnsureRequestObjectWithoutScopeFails.class,
		FAPIRWID2EnsureRequestObjectWithoutState.class,
		FAPIRWID2EnsureRequestObjectWithoutNonceFails.class,
		FAPIRWID2EnsureRequestObjectWithoutRedirectUriFails.class,
		FAPIRWID2EnsureExpiredRequestObjectFails.class,
		FAPIRWID2EnsureRequestObjectWithBadAudFails.class,
		FAPIRWID2EnsureSignedRequestObjectWithRS256Fails.class,
		FAPIRWID2EnsureRequestObjectSignatureAlgorithmIsNotNone.class,
		FAPIRWID2EnsureMatchingKeyInAuthorizationRequest.class,
		FAPIRWID2OBEnsureRequestObjectWithoutExpFailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutScopeFailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutStateWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutNonceFailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutRedirectUriFailsWithMTLS.class,
		FAPIRWID2OBEnsureExpiredRequestObjectFailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithBadAudFailsWithMTLS.class,
		FAPIRWID2OBEnsureSignedRequestObjectWithRS256FailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectSignatureAlgorithmIsNotNoneWithMTLS.class,
		FAPIRWID2OBEnsureMatchingKeyInAuthorizationRequestWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutExpFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutScopeFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutStateWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutNonceFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutRedirectUriFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureExpiredRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithBadAudFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureSignedRequestObjectWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectSignatureAlgorithmIsNotNoneWithPrivateKeyAndMTLS.class,
		FAPIRWID2OBEnsureMatchingKeyInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey.class,

		// Negative tests for authorization request
		FAPIRWID2EnsureAuthorizationRequestWithoutRequestObjectFails.class,
		FAPIRWID2EnsureRedirectUriInAuthorizationRequest.class,
		FAPIRWID2EnsureResponseTypeCodeFails.class,
		FAPIRWID2OBEnsureAuthorizationRequestWithoutRequestObjectFailsWithMTLS.class,
		FAPIRWID2OBEnsureRedirectUriInAuthorizationRequestWithMTLS.class,
		FAPIRWID2OBEnsureResponseTypeCodeFailsWithMTLS.class,
		FAPIRWID2OBEnsureAuthorizationRequestWithoutRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRedirectUriInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureResponseTypeCodeFailsWithPrivateKeyAndMTLSHolderOfKey.class,

		// Negative tests for token endpoint
		FAPIRWID2EnsureClientIdInTokenEndpointWithMTLS.class,
		FAPIRWID2EnsureMTLSHolderOfKeyRequiredWithMTLS.class,
		FAPIRWID2EnsureAuthorizationCodeIsBoundToClient.class,
		FAPIRWID2EnsureClientIdInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureMTLSHolderOfKeyRequiredWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureClientIdInTokenEndpointWithMTLS.class,
		FAPIRWID2OBEnsureMTLSHolderOfKeyRequiredWithMTLS.class,
		FAPIRWID2OBEnsureAuthorizationCodeIsBoundToClientWithMTLS.class,
		FAPIRWID2OBEnsureClientIdInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureMTLSHolderOfKeyRequiredWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureAuthorizationCodeIsBoundToClientIsBoundToClientWithPrivateKeyAndMTLSHolderOfKey.class,

		// Private key specific tests
		FAPIRWID2EnsureSignedClientAssertionWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureClientAssertionInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureSignedClientAssertionWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureClientAssertionInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey.class,

		// OB systems specific tests
		FAPIRWID2OBEnsureServerHandlesNonMatchingIntentIdWithMTLS.class,
		FAPIRWID2OBEnsureServerHandlesNonMatchingIntentIdWithPrivateKeyAndMTLSHolderOfKey.class
	},
	variants = {
		FAPIRWID2.variant_mtls,
		FAPIRWID2.variant_privatekeyjwt,
		FAPIRWID2.variant_openbankinguk_mtls,
		FAPIRWID2.variant_openbankinguk_privatekeyjwt
	}
)
public class FAPI_RW_ID2_V3_0_7_TestPlan implements TestPlan {

}
