package io.fintechlabs.testframework.fapi;

import io.fintechlabs.testframework.openbanking.FAPIRWID2OBDiscoveryEndpointVerification;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationCodeIsBoundToClientIsBoundToClientWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationCodeIsBoundToClientWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationRequestWithoutRequestObjectFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationRequestWithoutRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationRequestWithoutStateSuccessWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureAuthorizationRequestWithoutStateSuccessWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureClientAssertionInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureClientIdInTokenEndpointWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureClientIdInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureDifferentNonceInsideAndOutsideRequestObjectWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureDifferentNonceInsideAndOutsideRequestObjectWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureExpiredRequestObjectFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureExpiredRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureMTLSHolderOfKeyRequiredWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureMTLSHolderOfKeyRequiredWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureMatchingKeyInAuthorizationRequestWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureMatchingKeyInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRedirectUriInAuthorizationRequestWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRedirectUriInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRegisteredRedirectUriWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRegisteredRedirectUriWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectSignatureAlgorithmIsNotNoneWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectSignatureAlgorithmIsNotNoneWithPrivateKeyAndMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithBadAudFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithBadAudFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithMultipleAudSucceedsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithMultipleAudSucceedsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutExpFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutExpFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutNonceFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutNonceFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutRedirectUriFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutRedirectUriFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutScopeFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutScopeFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutStateWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureRequestObjectWithoutStateWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureResponseModeQueryWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureResponseModeQueryWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureResponseTypeCodeFailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureResponseTypeCodeFailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureServerHandlesNonMatchingIntentIdWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureServerHandlesNonMatchingIntentIdWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureSignedClientAssertionWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureSignedRequestObjectWithRS256FailsWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBEnsureSignedRequestObjectWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBRefreshTokenWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBRefreshTokenWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBUserRejectsAuthenticationWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBUserRejectsAuthenticationWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBWithMTLS;
import io.fintechlabs.testframework.openbanking.FAPIRWID2OBWithPrivateKeyAndMTLSHolderOfKey;
import io.fintechlabs.testframework.plan.PublishTestPlan;
import io.fintechlabs.testframework.plan.TestPlan;

@PublishTestPlan (
	testPlanName = "fapi-rw-id2-test-plan",
	displayName = "FAPI-RW-ID2: Authorization server test",
	profile = "FAPI-RW-ID2-OpenID-Provider-Authorization-Server-Test",
	testModules = {
		// Normal well behaved client cases
		FAPIRWID2DiscoveryEndpointVerification.class,
		FAPIRWID2WithMTLS.class,
		FAPIRWID2UserRejectsAuthenticationWithMTLS.class,
		FAPIRWID2EnsureServerAcceptsRequestObjectWithMultipleAudWithMTLS.class,
		FAPIRWID2EnsureAuthorizationRequestWithoutStateSuccessWithMTLS.class,
		FAPIRWID2WithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2UserRejectsAuthenticationWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureServerAcceptsRequestObjectWithMultipleAudWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureAuthorizationRequestWithoutStateSuccessWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBDiscoveryEndpointVerification.class,
		FAPIRWID2OBWithMTLS.class,
		FAPIRWID2OBUserRejectsAuthenticationWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithMultipleAudSucceedsWithMTLS.class,
		FAPIRWID2OBEnsureAuthorizationRequestWithoutStateSuccessWithMTLS.class,
		FAPIRWID2OBWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBUserRejectsAuthenticationWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithMultipleAudSucceedsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureAuthorizationRequestWithoutStateSuccessWithPrivateKeyAndMTLSHolderOfKey.class,

		// Possible failure case
		FAPIRWID2EnsureResponseModeQueryWithMTLS.class,
		FAPIRWID2EnsureDifferentNonceInsideAndOutsideRequestObjectWithMTLS.class,
		FAPIRWID2EnsureRegisteredRedirectUriWithMTLS.class,
		FAPIRWID2EnsureResponseModeQueryWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureDifferentNonceInsideAndOutsideRequestObjectWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureRegisteredRedirectUriWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureResponseModeQueryWithMTLS.class,
		FAPIRWID2OBEnsureDifferentNonceInsideAndOutsideRequestObjectWithMTLS.class,
		FAPIRWID2OBEnsureRegisteredRedirectUriWithMTLS.class,
		FAPIRWID2OBEnsureResponseModeQueryWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureDifferentNonceInsideAndOutsideRequestObjectWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRegisteredRedirectUriWithPrivateKeyAndMTLSHolderOfKey.class,

		// Negative tests for request objects
		FAPIRWID2EnsureRequestObjectWithoutExpFailsWithMTLS.class,
		FAPIRWID2EnsureRequestObjectWithoutScopeFailsWithMTLS.class,
		FAPIRWID2EnsureRequestObjectWithoutStateWithMTLS.class,
		FAPIRWID2EnsureRequestObjectWithoutNonceFailsWithMTLS.class,
		FAPIRWID2EnsureRequestObjectWithoutRedirectUriFailsWithMTLS.class,
		FAPIRWID2EnsureExpiredRequestObjectFailsWithMTLS.class,
		FAPIRWID2EnsureRequestObjectWithBadAudFailsWithMTLS.class,
		FAPIRWID2EnsureSignedRequestObjectWithRS256FailsWithMTLS.class,
		FAPIRWID2EnsureRequestObjectSignatureAlgorithmIsNotNoneWithMTLS.class,
		FAPIRWID2EnsureMatchingKeyInAuthorizationRequestWithMTLS.class,
		FAPIRWID2EnsureRequestObjectWithoutExpFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureRequestObjectWithoutScopeFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureRequestObjectWithoutStateWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureRequestObjectWithoutNonceFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureRequestObjectWithoutRedirectUriFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureExpiredRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureRequestObjectWithBadAudFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureSignedRequestObjectWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureRequestObjectSignatureAlgorithmIsNotNoneWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureMatchingKeyInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutExpFailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutScopeFailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutStateWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutNonceFailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutRedirectUriFailsWithMTLS.class,
		FAPIRWID2OBEnsureExpiredRequestObjectFailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithBadAudFailsWithMTLS.class,
		FAPIRWID2OBEnsureSignedRequestObjectWithRS256FailsWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectSignatureAlgorithmIsNotNoneWithMTLS.class,
		FAPIRWID2OBEnsureMatchingKeyInAuthorizationRequestWithMTLS.class,
		FAPIRWID2OBEnsureRequestObjectWithoutExpFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutScopeFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutStateWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutNonceFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithoutRedirectUriFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureExpiredRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectWithBadAudFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureSignedRequestObjectWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRequestObjectSignatureAlgorithmIsNotNoneWithPrivateKeyAndMTLS.class,
		FAPIRWID2OBEnsureMatchingKeyInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey.class,

		// Negative tests for authorization request
		FAPIRWID2EnsureAuthorizationRequestWithoutRequestObjectFailsWithMTLS.class,
		FAPIRWID2EnsureRedirectUriInAuthorizationRequestWithMTLS.class,
		FAPIRWID2EnsureResponseTypeCodeFailsWithMTLS.class,
		FAPIRWID2EnsureAuthorizationRequestWithoutRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureRedirectUriInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureResponseTypeCodeFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureAuthorizationRequestWithoutRequestObjectFailsWithMTLS.class,
		FAPIRWID2OBEnsureRedirectUriInAuthorizationRequestWithMTLS.class,
		FAPIRWID2OBEnsureResponseTypeCodeFailsWithMTLS.class,
		FAPIRWID2OBEnsureAuthorizationRequestWithoutRequestObjectFailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureRedirectUriInAuthorizationRequestWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureResponseTypeCodeFailsWithPrivateKeyAndMTLSHolderOfKey.class,

		// Negative tests for token endpoint
		FAPIRWID2EnsureClientIdInTokenEndpointWithMTLS.class,
		FAPIRWID2EnsureMTLSHolderOfKeyRequiredWithMTLS.class,
		FAPIRWID2EnsureAuthorizationCodeIsBoundToClientWithMTLS.class,
		FAPIRWID2EnsureClientIdInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureMTLSHolderOfKeyRequiredWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureAuthorizationCodeIsBoundToClientWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureClientIdInTokenEndpointWithMTLS.class,
		FAPIRWID2OBEnsureMTLSHolderOfKeyRequiredWithMTLS.class,
		FAPIRWID2OBEnsureAuthorizationCodeIsBoundToClientWithMTLS.class,
		FAPIRWID2OBEnsureClientIdInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureMTLSHolderOfKeyRequiredWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureAuthorizationCodeIsBoundToClientIsBoundToClientWithPrivateKeyAndMTLSHolderOfKey.class,

		// Private key specific tests
		FAPIRWID2EnsureSignedClientAssertionWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2EnsureClientAssertionInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureSignedClientAssertionWithRS256FailsWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBEnsureClientAssertionInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey.class,

		//Refresh token tests
		FAPIRWID2RefreshTokenWithMTLS.class,
		FAPIRWID2RefreshTokenTestWithPrivateKeyAndMTLSHolderOfKey.class,
		FAPIRWID2OBRefreshTokenWithMTLS.class,
		FAPIRWID2OBRefreshTokenWithPrivateKeyAndMTLSHolderOfKey.class,

		// OB systems specific tests
		FAPIRWID2OBEnsureServerHandlesNonMatchingIntentIdWithMTLS.class,
		FAPIRWID2OBEnsureServerHandlesNonMatchingIntentIdWithPrivateKeyAndMTLSHolderOfKey.class
	},
	variants = {
		FAPIRWID2.variant_mtls,
		FAPIRWID2.variant_privatekeyjwt,
		FAPIRWID2.variant_openbankinguk_mtls,
		FAPIRWID2.variant_openbankinguk_privatekeyjwt
	}
)
public class FAPI_RW_ID2_TestPlan implements TestPlan {

}
