package net.openid.conformance.vci10wallet.condition;

import com.google.gson.JsonObject;
import net.openid.conformance.condition.AbstractCondition;
import net.openid.conformance.testmodule.Environment;
import net.openid.conformance.testmodule.OIDFJSON;

public class VCIResolveRequestedCredentialConfigurationFromRequest extends AbstractCondition {

	@Override
	public Environment evaluate(Environment env) {

		var incomingRequest = env.getObject("incoming_request");
		var requestBodyJson = incomingRequest.getAsJsonObject("body_json");

		var credentialConfigurationsSupported = env.getElementFromObject("credential_issuer_metadata", "credential_configurations_supported").getAsJsonObject();

		JsonObject resolvedCredentialConfiguration = null;
		String resolvedCredentialConfigurationId = null;
		if (requestBodyJson.has("credential_identifier")) {
			// lookup credential_configuration by credential_identifier
			String credentialIdentifier = OIDFJSON.getString(requestBodyJson.get("credential_identifier"));

			if (!credentialIdentifier.contains(":")) {
				throw error("Invalid credential_identifier provided in request. Credential identifiers generated by this testsuite follow the pattern 'credential_configuration_id:random_uuid'",
					args("credential_identifier", credentialIdentifier));
			}
			String[] parts = credentialIdentifier.split(":");
			resolvedCredentialConfigurationId = parts[0].trim();
			JsonObject credentialConfiguration = credentialConfigurationsSupported.getAsJsonObject(resolvedCredentialConfigurationId);
			resolvedCredentialConfiguration = credentialConfiguration;

			log("Found requested credential_configuration via credential_identifier " + credentialIdentifier,
				args("credential_configuration", credentialConfiguration, "credential_identifier", credentialIdentifier));
		} else if (requestBodyJson.has("credential_configuration_id")) {
			// lookup credential_configuration by credential_configuration_id
			resolvedCredentialConfigurationId = OIDFJSON.getString(requestBodyJson.get("credential_configuration_id"));
			JsonObject credentialConfiguration = credentialConfigurationsSupported.getAsJsonObject(resolvedCredentialConfigurationId);
			resolvedCredentialConfiguration = credentialConfiguration;
			log("Found requested credential_configuration via credential_configuration_id " + resolvedCredentialConfigurationId,
				args("credential_configuration", credentialConfiguration, "credential_configuration_id", resolvedCredentialConfigurationId));
		}

		if (resolvedCredentialConfiguration == null) {
			throw error("Could not resolve requested credential_configuration",
				args("credential_identifier", requestBodyJson.get("credential_identifier"), "credential_configuration_id", requestBodyJson.get("credential_configuration_id")));
		}

		env.putString("credential_configuration_id", resolvedCredentialConfigurationId);
		env.putObject("credential_configuration", resolvedCredentialConfiguration);

		logSuccess("Resolved requested credential_configuration to " + resolvedCredentialConfigurationId,
			args("credential_configuration", resolvedCredentialConfiguration));

		return env;
	}
}
