#!/usr/bin/env bash
#
# Regenerate frontend/package-lock.json in an isolated Linux environment that
# matches CI. Use after changing frontend/package.json (adding, removing, or
# bumping a dependency).
#
# Why this script exists:
#   `npm install` on macOS produces a platform-biased lockfile: npm records
#   only the OS-specific optional deps that apply to the host platform, and
#   omits the Linux binaries (esbuild, rollup, lightningcss, …) that CI needs.
#   The result installs fine on the contributor's laptop, passes `npm ci`
#   locally on macOS, and then breaks GitLab CI inside node:22-alpine with
#   `npm ci` "Missing: X from lock file" / "Invalid: Y does not satisfy Z"
#   errors -- often for packages like react, @testing-library/dom, valibot
#   that arrive as optional peer deps.
#
#   Regenerating inside the CI image produces a lockfile that works for
#   every platform: `npm ci` succeeds on macOS, Linux, and Windows, because
#   each runtime only reifies the optional packages relevant to its OS.
#
# Usage:
#   cd frontend && ./scripts/regen-lockfile.sh
#
# Requirements:
#   Docker Desktop (or any Docker-compatible runtime). No Node/npm needed on
#   the host -- npm 11.12.1 is activated inside the container via Corepack so
#   the lockfile always matches the `packageManager` pin in package.json.
#
# After running, commit only frontend/package-lock.json (frontend/package.json
# should already reflect your intended dependency change).

set -euo pipefail

# Mirror the image used by GitLab CI's frontend_lint job. Keep in sync with
# .gitlab-ci.yml's `image: node:22-alpine` entry.
IMAGE="node:22-alpine"

# Keep in sync with the `packageManager` field in frontend/package.json.
# Corepack downloads this version on demand and shims `npm` so the lockfile
# is always generated by the pinned version, regardless of what ships with
# the Node image.
NPM_VERSION="11.12.1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONTEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: docker is required but not found in PATH." >&2
  echo "Install Docker Desktop or set up a Docker-compatible runtime, then retry." >&2
  exit 1
fi

echo "Regenerating frontend/package-lock.json inside ${IMAGE} with npm@${NPM_VERSION}..."

docker run --rm \
  -v "${FRONTEND_DIR}:/w" \
  -w /w \
  "${IMAGE}" \
  sh -c "
    set -eu
    corepack enable npm
    corepack prepare npm@${NPM_VERSION} --activate >/dev/null
    echo \"Using npm \$(npm --version)\"
    rm -rf node_modules package-lock.json
    npm install --ignore-scripts
  "

# node_modules is left in place so the contributor can continue working
# immediately; only the lockfile change should be committed.
echo ""
echo "Done. Review the diff and commit only frontend/package-lock.json:"
echo "  git diff --stat frontend/package-lock.json"
echo "  git add frontend/package-lock.json"
echo "  git commit -m 'chore(frontend): regenerate package-lock.json'"
