package io.fintechlabs.testframework.fapiciba;

import io.fintechlabs.testframework.plan.PublishTestPlan;
import io.fintechlabs.testframework.plan.TestPlan;

@PublishTestPlan (
	testPlanName = "fapi-ciba-poll-with-mtls-test-plan",
	displayName = "FAPI-CIBA: poll with mtls client authentication test plan",
	profile = "FAPI-CIBA",
	testModules = {
		FAPICIBAPollDiscoveryEndpointVerification.class,
		FAPICIBAPollWithMTLS.class,
		FAPICIBAPollUserRejectsAuthenticationWithMTLS.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectMissingAudFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectBadAudFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectMissingIssFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectBadIssFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectMissingExpFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectExpiredExpFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectExpIsYearInFutureFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectMissingIatFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectIatIsWeekInPastFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectIatIsHourInFutureFails.class,
		FAPICIBAPollWithMTLSEnsureRequestObjectMissingJtiFails.class,
		FAPICIBAPollEnsureAuthorizationRequestWithMultipleHintsFailsWithMTLS.class,
		FAPICIBAPollEnsureRequestObjectSignatureAlgorithmIsNoneFailsWithMTLS.class,
		FAPICIBAPollEnsureRequestObjectSignatureAlgorithmIsBadFailsWithMTLS.class,
		FAPICIBAPollEnsureRequestObjectSignatureAlgorithmIsRS256FailsWithMTLS.class,
		FAPICIBAPollEnsureRequestObjectSignedByOtherClientFailsWithMTLS.class,
		FAPICIBAPollEnsureAuthorizationRequestWithBindingMessageSucceedsWithMTLS.class,
		FAPICIBAPollEnsureAuthorizationRequestWithPotentiallyBadBindingMessageWithMTLS.class,
		FAPICIBAPollAuthReqIdExpiredWithMTLS.class,
		FAPICIBAPollEnsureBackchannelAuthorizationRequestWithoutRequestFailsWithMTLS.class,
		FAPICIBAPollMultipleCallToTokenEndpointWithMTLS.class,
		FAPICIBAPollEnsureDifferentClientIdAndIssuerInBackchannelAuthorizationRequestWithMTLS.class,
		FAPICIBAPollEnsureWrongClientIdInTokenEndpointRequestWithMTLS.class,
		FAPICIBAPollEnsureWrongClientIdInBackchannelAuthorizationRequestWithMTLS.class,
		FAPICIBAPollEnsureWrongAuthenticationRequestIdInTokenEndpointRequestWithMTLS.class,
	}
)
public class FAPICIBAPollWithMTLSTestPlan implements TestPlan {

}
