package net.openid.conformance.info;

import com.google.common.base.Strings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import java.util.regex.Pattern;

/**
 * Serves Playwright trace archives from the directory the scripted browser writes them to
 * ({@code browser.playwright.tracesDir}, one {@code <testId>.zip} per test).
 */
@Service
public class FileTraceService implements TraceService {

	private static final Logger logger = LoggerFactory.getLogger(FileTraceService.class);

	// test ids are generated by RandomStringUtils.randomAlphanumeric; anything else would be a
	// crafted id and must not be turned into a path
	private static final Pattern TEST_ID = Pattern.compile("[A-Za-z0-9]+");

	@Value("${browser.playwright.tracesDir:}")
	private String tracesDir;

	@Override
	public Optional<byte[]> getTraceForTestId(String testId) {
		Optional<Path> tracePath = tracePath(testId);
		if (tracePath.isEmpty() || !Files.isRegularFile(tracePath.get())) {
			return Optional.empty();
		}

		try {
			return Optional.of(Files.readAllBytes(tracePath.get()));
		} catch (IOException e) {
			logger.error("Failed to read trace for testId: {}", testId, e);
			return Optional.empty();
		}
	}

	@Override
	public void deleteTraceForTestId(String testId) {
		Optional<Path> tracePath = tracePath(testId);
		if (tracePath.isEmpty()) {
			return;
		}

		try {
			if (Files.deleteIfExists(tracePath.get())) {
				logger.debug("Deleted trace for testId: {}", testId);
			}
		} catch (IOException e) {
			logger.error("Failed to delete trace for testId: {}", testId, e);
		}
	}

	/**
	 * The path a test's trace is at, or empty if traces aren't configured or the id isn't one of
	 * ours. The id is only ever turned into a path if it is plain alphanumeric, so it can't leave
	 * the traces directory or name anything but a {@code <testId>.zip} in it.
	 */
	private Optional<Path> tracePath(String testId) {
		if (Strings.isNullOrEmpty(tracesDir)) {
			return Optional.empty();
		}
		if (testId == null || !TEST_ID.matcher(testId).matches()) {
			logger.debug("Refusing to turn malformed testId into a trace path: {}", testId);
			return Optional.empty();
		}
		return Optional.of(Path.of(tracesDir).resolve(testId + ".zip"));
	}
}
