package net.openid.conformance.info;

import com.google.common.base.Strings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import java.util.regex.Pattern;

/**
 * Serves Playwright trace archives from the directory the scripted browser writes them to
 * ({@code browser.playwright.tracesDir}, one {@code <testId>.zip} per test).
 */
@Service
public class FileTraceService implements TraceService {

	private static final Logger logger = LoggerFactory.getLogger(FileTraceService.class);

	// test ids are generated by RandomStringUtils.randomAlphanumeric; anything else would be a
	// crafted id and must not be turned into a path
	private static final Pattern TEST_ID = Pattern.compile("[A-Za-z0-9]+");

	@Value("${browser.playwright.tracesDir:}")
	private String tracesDir;

	@Override
	public Optional<byte[]> getTraceForTestId(String testId) {
		if (Strings.isNullOrEmpty(tracesDir)) {
			return Optional.empty();
		}
		if (testId == null || !TEST_ID.matcher(testId).matches()) {
			logger.debug("Refusing to look up trace for malformed testId: {}", testId);
			return Optional.empty();
		}

		Path tracePath = Path.of(tracesDir).resolve(testId + ".zip");
		if (!Files.isRegularFile(tracePath)) {
			return Optional.empty();
		}

		try {
			return Optional.of(Files.readAllBytes(tracePath));
		} catch (IOException e) {
			logger.error("Failed to read trace for testId: {}", testId, e);
			return Optional.empty();
		}
	}
}
