package io.fintechlabs.testframework.openbanking;

import io.fintechlabs.testframework.plan.PublishTestPlan;
import io.fintechlabs.testframework.plan.TestPlan;

@PublishTestPlan (
	testPlanName = "fapi-rw-id2-ob-client-test-with-private-key-jwt-and-mtls-holder-of-key-test-plan",
	displayName = "FAPI-RW-ID2-OpenBankingUK: Relying Party (client test) using private_key_jwt client authentication",
	profile = "FAPI-RW-ID2-OpenBankingUK-Relying-Party-Client-Test",
	testModules = {
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKey.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyNoAtHash.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidSHash.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidCHash.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidNonce.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidIss.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidAud.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidSecondaryAud.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidOpenBankingIntentId.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidSignature.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidNullAlg.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidAlternateAlg.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidMissingExp.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidExpiredExp.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyIatIsWeekInPast.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidMissingAud.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidMissingIss.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidMissingNonce.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyInvalidMissingSHash.class,
		FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyValidAudAsArray.class
	}
)
public class FAPIRWID2OBClientTestWithPrivateKeyJWTAndMTLSHolderOfKeyTestPlan implements TestPlan {

}
