package net.openid.conformance.openid.ssf;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import net.openid.conformance.condition.Condition;
import net.openid.conformance.openid.ssf.conditions.OIDSSFFindingCondition;
import net.openid.conformance.openid.ssf.conditions.OIDSSFLogSuccessCondition;
import net.openid.conformance.openid.ssf.conditions.events.OIDSSFSecurityEvent;
import net.openid.conformance.openid.ssf.conditions.streams.OIDSSFGenerateStreamSET;
import net.openid.conformance.openid.ssf.conditions.streams.OIDSSFStreamUtils;
import net.openid.conformance.testmodule.OIDFJSON;
import net.openid.conformance.testmodule.PublishTestModule;

import java.time.Instant;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.ConcurrentSkipListSet;
import java.util.concurrent.TimeUnit;

@PublishTestModule(
	testName = "openid-ssf-receiver-stream-supported-events",
	displayName = "OpenID Shared Signals Framework: Sends all supported events to the receiver",
	summary = """
		This test verifies the receiver events delivery.
		The test generates a dynamic transmitter and waits for a receiver to register a stream and verify it; once verified, it generates all supported events and expects a positive delivery of the events received.
		Each delivered event type is sent once per subject declared in the 'SSF valid SubjectId' field,
		except the SSF framework events (verification, stream-updated), which identify the stream itself
		and are sent once with the stream's opaque subject (SSF 1.0 8.1.4.1, 8.1.5).
		Note that if the caep_interop profile is used, only the CAEP Interop Profile event types (session-revoked, credential-change, device-compliance-change and risk-level-change) are available, and only email/iss_sub (and complex) subjects are used.
		The testsuite expects to observe the following interactions:
		 * create a stream
		 * verify the stream
		 * (generates) events
		 * Acknowledge the events
		 * delete the stream
		""",
	profile = "OIDSSF"
)
public class OIDSSFReceiverSupportedEventsTest extends AbstractOIDSSFReceiverTestModule {

	volatile String createdStreamId;

	volatile String verificationStreamId;

	volatile String deletedStreamId;

	volatile JsonObject lastCreateResult;

	volatile ConcurrentMap<String, Set<String>> eventsAcked;

	volatile ConcurrentMap<String, Set<String>> eventsEnqueued;

	@Override
	public void start() {
		super.start();
		eventsAcked = new ConcurrentHashMap<>();
		eventsEnqueued = new ConcurrentHashMap<>();
		scheduleTask(new CheckTestFinishedTask(this::isFinished), 10, TimeUnit.SECONDS);
	}

	@Override
	protected void afterPushDeliverySuccess(String streamId, OIDSSFSecurityEvent event) {
		// PUSH delivery: the abstract base pushes the verification SET to the receiver
		// after the receiver hits the verify endpoint. Detect the first verification
		// event push and treat it as our cue to start sending the supported events.
		if (SsfEvents.isVerificationEvent(event.type()) && verificationStreamId == null) {
			verificationStreamId = streamId;
			callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected Stream Verification via PUSH delivery for stream_id=" + streamId), Condition.ConditionResult.FAILURE, "OIDSSF-8.1.4.1");
			afterInitialStreamVerification(streamId);
			return;
		}

		// Track non-verification events as acknowledged when successfully pushed
		eventsAcked.computeIfAbsent(streamId, k -> new ConcurrentSkipListSet<>()).add(event.jti());

		if (didReceiveExpectedAcksForAllDeliveredEvents()) {
			callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected expected delivery & ack notifications for stream_id=" + streamId), Condition.ConditionResult.FAILURE);
		}
	}

	@Override
	protected void onStreamEventAcknowledged(String streamId, String jti, OIDSSFSecurityEvent event) {
		// POLL delivery: the receiver polls the events endpoint and acknowledges what it
		// received. The first ack will be for the verification SET (generated by the verify
		// endpoint handler in the abstract base); use that as our cue to start sending the
		// supported events.
		if (SsfEvents.isVerificationEvent(event.type()) && verificationStreamId == null) {
			verificationStreamId = streamId;
			callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected Stream Verification via POLL delivery for stream_id=" + streamId), Condition.ConditionResult.FAILURE, "OIDSSF-8.1.4.1");
			scheduleAfterStreamVerification(() -> afterInitialStreamVerification(streamId));
			return;
		}

		eventsAcked.computeIfAbsent(streamId, k -> new ConcurrentSkipListSet<>()).add(jti);

		if (didReceiveExpectedAcksForAllDeliveredEvents()) {
			callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected expected delivery & ack notifications for stream_id=" + streamId), Condition.ConditionResult.FAILURE);
		}
	}

	@Override
	protected void onStreamEventEnqueued(String streamId, String jti) {
		eventsEnqueued.computeIfAbsent(streamId, k -> new ConcurrentSkipListSet<>()).add(jti);
	}

	@Override
	protected void afterStreamCreation(String streamId, JsonObject createResult, JsonElement error) {

		if (createResult == null) {
			return;
		}

		createdStreamId = streamId;
		lastCreateResult = createResult;
		callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected Stream creation for stream_id=" + streamId), Condition.ConditionResult.FAILURE, "OIDSSF-8.1.1.1");

		// Event generation is deferred to afterInitialStreamVerification so the test mirrors the
		// real flow: the receiver creates the stream, verifies it, and only then does the
		// transmitter start sending events. This also ensures PUSH-delivery streams have a
		// valid push trigger (the verify endpoint handler already kicks the push task).
	}

	protected void afterInitialStreamVerification(String streamId) {
		if (lastCreateResult == null) {
			return;
		}

		// All subjects declared in 'SSF valid SubjectId' (under the CAEP Interop Profile restricted to
		// the email/iss_sub formats) — see AbstractOIDSSFReceiverTestModule#getEventSubjects.
		List<JsonObject> subjects = getEventSubjects();
		List<String> eventsDelivered = OIDFJSON.convertJsonArrayToList(lastCreateResult.getAsJsonObject("result").getAsJsonArray("events_delivered"));

		long timestamp = Instant.now().getEpochSecond();

		for (String eventType : eventsDelivered) {

			if (SsfEvents.SSF_EVENT_TYPES.contains(eventType)) {
				// The SSF framework events are about the stream, not about a subject: their
				// sub_id MUST be the opaque stream id (SSF 1.0 8.1.4.1, 8.1.5), and a verification
				// event the transmitter initiates MUST NOT carry a state (8.1.4.2). One SET each.
				SsfEvent event = generateSsfFrameworkEventExample(eventType, streamId);
				var generateStreamSET = new OIDSSFGenerateStreamSET(eventStore, streamId, streamSubject(streamId), event, this::onStreamEventEnqueued);
				callAndContinueOnFailure(generateStreamSET, Condition.ConditionResult.WARNING, event.requirements().toArray(new String[0]));
				continue;
			}

			for (JsonObject subject : subjects) {
				SsfEvent event = generateSsfEventExample(eventType, timestamp);

				var generateStreamSET = new OIDSSFGenerateStreamSET(eventStore, streamId, subject, event, this::onStreamEventEnqueued);
				callAndContinueOnFailure(generateStreamSET, Condition.ConditionResult.WARNING, event.requirements().toArray(new String[0]));
			}
		}
	}

	private static JsonObject streamSubject(String streamId) {
		JsonObject subject = new JsonObject();
		subject.addProperty("format", "opaque");
		subject.addProperty("id", streamId);
		return subject;
	}

	/**
	 * Event data for the SSF framework event types when they are delivered as "supported
	 * events": a transmitter-initiated verification event has no claims (SSF 1.0 8.1.4.2 forbids
	 * a state), a stream-updated event reports the stream's current status (8.1.5: status REQUIRED).
	 */
	private SsfEvent generateSsfFrameworkEventExample(String eventType, String streamId) {
		if (SsfEvents.SSF_STREAM_UPDATED_EVENT_TYPE.equals(eventType)) {
			JsonObject streamConfig = OIDSSFStreamUtils.getStreamConfig(env, streamId);
			JsonObject streamStatus = streamConfig == null ? null : OIDSSFStreamUtils.getStreamStatus(streamConfig);
			String status = streamStatus == null
				? OIDSSFStreamUtils.StreamStatusValue.enabled.name()
				: OIDFJSON.getString(streamStatus.get("status"));
			return new SsfEvent(eventType,
				Map.of("status", status, "reason", "Stream status reported as a supported event"),
				Set.of("OIDSSF-8.1.5"));
		}
		return new SsfEvent(eventType, Map.of(), Set.of("OIDSSF-8.1.4", "OIDSSF-8.1.4.2"));
	}

	@Override
	protected void afterStreamDeletion(String streamId, JsonObject deleteResult, JsonElement error) {
		if (error != null || streamId == null) {
			// deletion failed (e.g. 404 for an unknown or already-deleted stream) - do not
			// record it as the successful deletion or reset previously recorded state
			return;
		}
		deletedStreamId = streamId;
		callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected Stream deletion for stream_id=" + streamId), Condition.ConditionResult.FAILURE, "OIDSSF-8.1.1.5");
	}

	@Override
	protected boolean isFinished() {
		return createdStreamId != null
			&& eventsEnqueued.get(createdStreamId) != null
			&& didReceiveExpectedAcksForAllDeliveredEvents()
			&& createdStreamId.equals(deletedStreamId);
	}

	protected boolean didReceiveExpectedAcksForAllDeliveredEvents() {
		if (createdStreamId == null || eventsEnqueued.get(createdStreamId) == null) {
			return false;
		}
		// Events for which no acknowledgement can arrive any more (never delivered, resolved
		// via setErrs, push delivery rejected, or left unresolved when the receiver deleted
		// the stream) must not stall the test until it times out - whether every delivered
		// event was actually acknowledged is judged in fireTestFinished.
		Set<String> expectedAcks = new LinkedHashSet<>(eventsEnqueued.get(createdStreamId));
		expectedAcks.removeAll(getResolvedWithoutAckJtis());
		return eventsAcked.getOrDefault(createdStreamId, Set.of()).containsAll(expectedAcks);
	}

	@Override
	public void fireTestFinished() {
		Set<String> unacknowledged = new LinkedHashSet<>(
			createdStreamId == null ? Set.of() : eventsEnqueued.getOrDefault(createdStreamId, Set.of()));
		unacknowledged.removeAll(createdStreamId == null ? Set.of() : eventsAcked.getOrDefault(createdStreamId, Set.of()));
		// Undeliverable events were never handed to the receiver, so it cannot be expected to
		// acknowledge them. Error reports via setErrs are a valid resolution (RFC 8936 2.4),
		// and rejected push deliveries are already graded by the RFC 8935 2.2 status check.
		// What remains are events the receiver retrieved but neither acknowledged nor reported
		// before deleting the stream - the acknowledgement failure graded below.
		unacknowledged.removeAll(getUndeliveredEventJtis());
		unacknowledged.removeAll(getErrorReportedEventJtis());
		unacknowledged.removeAll(getRejectedPushEventJtis());
		if (unacknowledged.isEmpty()) {
			eventLog.log(getName(), "Detected acknowledgements for published events.");
		} else {
			// The receiver retrieved (or was pushed) these events but deleted the stream
			// without ever acknowledging them - accepted SETs must be acknowledged via
			// 'ack' (RFC 8936 2.4) or a 202 response (RFC 8935 2.2).
			callAndContinueOnFailure(new OIDSSFFindingCondition(
					"The receiver never acknowledged " + unacknowledged.size() + " of the " + "delivered events before deleting the stream (jtis: " + unacknowledged + "). "
						+ "Receivers must acknowledge accepted SETs via 'ack' (RFC 8936 2.4) or a 202 response (RFC 8935 2.2)."),
				Condition.ConditionResult.FAILURE, "RFC8936-2.4");
		}
		super.fireTestFinished();
	}
}
