package net.openid.conformance.openid.ssf;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import net.openid.conformance.condition.Condition;
import net.openid.conformance.openid.ssf.conditions.OIDSSFFindingCondition;
import net.openid.conformance.openid.ssf.conditions.OIDSSFLogSuccessCondition;
import net.openid.conformance.openid.ssf.conditions.events.OIDSSFSecurityEvent;
import net.openid.conformance.openid.ssf.conditions.streams.OIDSSFGenerateStreamSET;
import net.openid.conformance.testmodule.OIDFJSON;
import net.openid.conformance.testmodule.PublishTestModule;

import java.time.Instant;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.ConcurrentSkipListSet;
import java.util.concurrent.TimeUnit;

@PublishTestModule(
	testName = "openid-ssf-receiver-stream-supported-events",
	displayName = "OpenID Shared Signals Framework: Sends all supported events to the receiver",
	summary = """
		This test verifies the receiver events delivery.
		The test generates a dynamic transmitter and waits for a receiver to register a stream and verify it; once verified, it generates all supported events and expects a positive delivery of the events received.
		Each delivered event type is sent once per subject declared in the 'SSF valid SubjectId' field.
		Note that if the caep_interop profile is used, only the CAEP Interop Profile event types (session-revoked, credential-change and device-compliance-change) are available, and only email/iss_sub (and complex) subjects are used.
		The testsuite expects to observe the following interactions:
		 * create a stream
		 * verify the stream
		 * (generates) events
		 * Acknowledge the events
		 * delete the stream
		""",
	profile = "OIDSSF"
)
public class OIDSSFReceiverSupportedEventsTest extends AbstractOIDSSFReceiverTestModule {

	volatile String createdStreamId;

	volatile String verificationStreamId;

	volatile String deletedStreamId;

	volatile JsonObject lastCreateResult;

	volatile ConcurrentMap<String, Set<String>> eventsAcked;

	volatile ConcurrentMap<String, Set<String>> eventsEnqueued;

	@Override
	public void start() {
		super.start();
		eventsAcked = new ConcurrentHashMap<>();
		eventsEnqueued = new ConcurrentHashMap<>();
		scheduleTask(new CheckTestFinishedTask(this::isFinished), 10, TimeUnit.SECONDS);
	}

	@Override
	protected void afterPushDeliverySuccess(String streamId, OIDSSFSecurityEvent event) {
		// PUSH delivery: the abstract base pushes the verification SET to the receiver
		// after the receiver hits the verify endpoint. Detect the first verification
		// event push and treat it as our cue to start sending the supported events.
		if (SsfEvents.isVerificationEvent(event.type()) && verificationStreamId == null) {
			verificationStreamId = streamId;
			callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected Stream Verification via PUSH delivery for stream_id=" + streamId), Condition.ConditionResult.FAILURE, "OIDSSF-8.1.4.1");
			afterInitialStreamVerification(streamId);
			return;
		}

		// Track non-verification events as acknowledged when successfully pushed
		eventsAcked.computeIfAbsent(streamId, k -> new ConcurrentSkipListSet<>()).add(event.jti());

		if (didReceiveExpectedAcksForAllDeliveredEvents()) {
			callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected expected delivery & ack notifications for stream_id=" + streamId), Condition.ConditionResult.FAILURE);
		}
	}

	@Override
	protected void onStreamEventAcknowledged(String streamId, String jti, OIDSSFSecurityEvent event) {
		// POLL delivery: the receiver polls the events endpoint and acknowledges what it
		// received. The first ack will be for the verification SET (generated by the verify
		// endpoint handler in the abstract base); use that as our cue to start sending the
		// supported events.
		if (SsfEvents.isVerificationEvent(event.type()) && verificationStreamId == null) {
			verificationStreamId = streamId;
			callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected Stream Verification via POLL delivery for stream_id=" + streamId), Condition.ConditionResult.FAILURE, "OIDSSF-8.1.4.1");
			scheduleAfterStreamVerification(() -> afterInitialStreamVerification(streamId));
			return;
		}

		eventsAcked.computeIfAbsent(streamId, k -> new ConcurrentSkipListSet<>()).add(jti);

		if (didReceiveExpectedAcksForAllDeliveredEvents()) {
			callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected expected delivery & ack notifications for stream_id=" + streamId), Condition.ConditionResult.FAILURE);
		}
	}

	@Override
	protected void onStreamEventEnqueued(String streamId, String jti) {
		eventsEnqueued.computeIfAbsent(streamId, k -> new ConcurrentSkipListSet<>()).add(jti);
	}

	@Override
	protected void afterStreamCreation(String streamId, JsonObject createResult, JsonElement error) {

		if (createResult == null) {
			return;
		}

		createdStreamId = streamId;
		lastCreateResult = createResult;
		callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected Stream creation for stream_id=" + streamId), Condition.ConditionResult.FAILURE, "OIDSSF-8.1.1.1");

		// Event generation is deferred to afterInitialStreamVerification so the test mirrors the
		// real flow: the receiver creates the stream, verifies it, and only then does the
		// transmitter start sending events. This also ensures PUSH-delivery streams have a
		// valid push trigger (the verify endpoint handler already kicks the push task).
	}

	protected void afterInitialStreamVerification(String streamId) {
		if (lastCreateResult == null) {
			return;
		}

		// All subjects declared in 'SSF valid SubjectId' (under the CAEP Interop Profile restricted to
		// the email/iss_sub formats) — see AbstractOIDSSFReceiverTestModule#getEventSubjects.
		List<JsonObject> subjects = getEventSubjects();
		List<String> eventsDelivered = OIDFJSON.convertJsonArrayToList(lastCreateResult.getAsJsonObject("result").getAsJsonArray("events_delivered"));

		long timestamp = Instant.now().getEpochSecond();

		for (String eventType : eventsDelivered) {

			for (JsonObject subject : subjects) {
				SsfEvent event = generateSsfEventExample(eventType, timestamp);

				var generateStreamSET = new OIDSSFGenerateStreamSET(eventStore, streamId, subject, event, this::onStreamEventEnqueued);
				callAndContinueOnFailure(generateStreamSET, Condition.ConditionResult.WARNING, event.requirements().toArray(new String[0]));
			}
		}
	}

	@Override
	protected void afterStreamDeletion(String streamId, JsonObject deleteResult, JsonElement error) {
		if (error != null || streamId == null) {
			// deletion failed (e.g. 404 for an unknown or already-deleted stream) - do not
			// record it as the successful deletion or reset previously recorded state
			return;
		}
		deletedStreamId = streamId;
		callAndContinueOnFailure(new OIDSSFLogSuccessCondition("Detected Stream deletion for stream_id=" + streamId), Condition.ConditionResult.FAILURE, "OIDSSF-8.1.1.5");
	}

	@Override
	protected boolean isFinished() {
		return createdStreamId != null
			&& eventsEnqueued.get(createdStreamId) != null
			&& didReceiveExpectedAcksForAllDeliveredEvents()
			&& createdStreamId.equals(deletedStreamId);
	}

	protected boolean didReceiveExpectedAcksForAllDeliveredEvents() {
		if (createdStreamId == null || eventsEnqueued.get(createdStreamId) == null) {
			return false;
		}
		// Events that could not be delivered because the receiver deleted the stream are never
		// acknowledged; waiting for them would stall the test until it times out. A receiver
		// that acknowledged nothing at all must not stall here either (its events all become
		// undeliverable on deletion) - whether every delivered event was actually acknowledged
		// is judged in fireTestFinished.
		Set<String> expectedAcks = new LinkedHashSet<>(eventsEnqueued.get(createdStreamId));
		expectedAcks.removeAll(getUndeliveredEventJtis());
		return eventsAcked.getOrDefault(createdStreamId, Set.of()).containsAll(expectedAcks);
	}

	@Override
	public void fireTestFinished() {
		Set<String> unacknowledged = new LinkedHashSet<>(
			createdStreamId == null ? Set.of() : eventsEnqueued.getOrDefault(createdStreamId, Set.of()));
		unacknowledged.removeAll(createdStreamId == null ? Set.of() : eventsAcked.getOrDefault(createdStreamId, Set.of()));
		// Events recorded as undeliverable were never (fully) delivered - the receiver
		// cannot be expected to acknowledge SETs it never received.
		unacknowledged.removeAll(getUndeliveredEventJtis());
		if (unacknowledged.isEmpty()) {
			eventLog.log(getName(), "Detected acknowledgements for published events.");
		} else {
			// The receiver retrieved (or was pushed) these events but deleted the stream
			// without ever acknowledging them - accepted SETs must be acknowledged via
			// 'ack' (RFC 8936 2.4) or a 202 response (RFC 8935 2.2).
			callAndContinueOnFailure(new OIDSSFFindingCondition(
					"The receiver never acknowledged " + unacknowledged.size() + " of the " + "delivered events before deleting the stream (jtis: " + unacknowledged + "). "
						+ "Receivers must acknowledge accepted SETs via 'ack' (RFC 8936 2.4) or a 202 response (RFC 8935 2.2)."),
				Condition.ConditionResult.FAILURE, "RFC8936-2.4");
		}
		super.fireTestFinished();
	}
}
