package net.openid.conformance.condition.as;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.nimbusds.jose.jwk.JWK;
import net.openid.conformance.condition.PostEnvironment;
import net.openid.conformance.testmodule.Environment;
import net.openid.conformance.testmodule.OIDFJSON;

import java.security.SecureRandom;
import java.text.ParseException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CreateSdJwtCredential extends AbstractCreateSdJwtCredential {

	/**
	 * Size of the Token Status List served by the emulated issuer. Status list indices are allocated
	 * from this range, so it must match the list generated by
	 * {@code VCIGenerateJwtStatusListToken} (which marks even indices valid).
	 */
	private static final int STATUS_LIST_ENTRIES = 256;

	private final SecureRandom random = new SecureRandom();

	public CreateSdJwtCredential() {
		super();
	}

	public CreateSdJwtCredential(Map<String, Object> additionalClaims) {
		super(additionalClaims);
	}

	@Override
	@PostEnvironment(required = "credential_issuance")
	public Environment evaluate(Environment env) {

		List<JWK> publicJWKs = resolveJwks(env);

		JsonObject credentialConfiguration = env.getObject("credential_configuration");
		String credentialType = OIDFJSON.getString(credentialConfiguration.get("vct"));

		// Allocate a distinct, unpredictable status list index for each credential so that the
		// credentials in a batch cannot be correlated through a shared status reference
		// (HAIP §6.1, Token Status List §12.5 / §13.3, RFC 9901 §10.1).
		List<Long> statusIndices = allocateStatusListIndices(publicJWKs.size());

		JsonArray credentials = new JsonArray();
		for (int i = 0; i < publicJWKs.size(); i++) {
			JWK publicJWK = publicJWKs.get(i);
			String sdJwt = createSdJwt(env, publicJWK, null, credentialType,
				credentialClaimsWithStatusIndex(statusIndices.get(i)));
			JsonObject credentialObj = new JsonObject();
			credentialObj.addProperty("credential", sdJwt);
			credentials.add(credentialObj);
		}

		JsonObject credentialIssuance = new JsonObject();
		credentialIssuance.add("credentials", credentials);
		env.putObject("credential_issuance", credentialIssuance);

		log("Created %s in SD-JWT VC format".formatted(credentialType),
			args("credentials", credentials, "credential_count", credentials.size()));

		return env;

	}

	@Override
	protected long issuanceTimeSeconds() {
		// Round down to the hour so a batch (or several same-dataset credentials) share a coarse,
		// low-entropy iat/exp rather than a precise timestamp that lets verifiers link them
		// (RFC 9901 §10.1). The issuer-side linkability checks treat an hour-boundary value as
		// "rounded" and pass it.
		long now = Instant.now().getEpochSecond();
		return now - (now % 3600L);
	}

	/**
	 * Picks {@code count} distinct, unpredictable status list indices from the served list. Only the
	 * even indices are used because {@code VCIGenerateJwtStatusListToken} marks even bits valid; the
	 * selection is shuffled rather than sequential so it does not form a predictable (arithmetic)
	 * sequence (HAIP §6.1, Token Status List §12.5.1).
	 */
	private List<Long> allocateStatusListIndices(int count) {
		List<Long> validIndices = new ArrayList<>();
		for (long i = 0; i < STATUS_LIST_ENTRIES; i += 2) {
			validIndices.add(i);
		}
		Collections.shuffle(validIndices, random);
		return validIndices.subList(0, Math.min(count, validIndices.size()));
	}

	/**
	 * Returns a copy of the configured additional claims with the {@code status.status_list.idx}
	 * replaced by {@code idx}, so each credential in a batch gets its own status list index. If no
	 * status list claim is present the base claims are returned unchanged.
	 */
	@SuppressWarnings("unchecked")
	private Map<String, Object> credentialClaimsWithStatusIndex(Long idx) {
		if (additionalClaims == null || idx == null) {
			return additionalClaims;
		}
		Object status = additionalClaims.get("status");
		if (!(status instanceof Map)) {
			return additionalClaims;
		}
		Object statusList = ((Map<Object, Object>) status).get("status_list");
		if (!(statusList instanceof Map)) {
			return additionalClaims;
		}
		Map<String, Object> claimsCopy = new HashMap<>(additionalClaims);
		Map<Object, Object> statusCopy = new HashMap<>((Map<Object, Object>) status);
		Map<Object, Object> statusListCopy = new HashMap<>((Map<Object, Object>) statusList);
		statusListCopy.put("idx", idx);
		statusCopy.put("status_list", statusListCopy);
		claimsCopy.put("status", statusCopy);
		return claimsCopy;
	}

	private JWK parseJwk(JsonElement jwkElement) {
		try {
			return JWK.parse(jwkElement.toString());
		} catch (ParseException e) {
			throw error("Failed to parse public JWK", e, args("jwk", jwkElement));
		}
	}

	/**
	 * Resolves all device public keys from the proof.
	 * Per VCI spec F.1 and F.3, the issuer SHOULD issue a Credential for each
	 * cryptographic public key specified in the attested_keys claim or for each
	 * key in the jwt proofs array.
	 *
	 * @return List of JWKs (may contain a single null if no cryptographic binding is required)
	 */
	protected List<JWK> resolveJwks(Environment env) {

		// Check if the credential configuration requires cryptographic binding
		JsonObject credentialConfiguration = env.getObject("credential_configuration");
		if (credentialConfiguration != null && !credentialConfiguration.has("cryptographic_binding_methods_supported")) {
			// No cryptographic binding required, no cnf claim needed
			log("Credential configuration does not require cryptographic binding, skipping cnf claim");
			List<JWK> result = new ArrayList<>();
			result.add(null);
			return result;
		}

		String proofType = env.getString("proof_type");

		List<JWK> publicJWKs = new ArrayList<>();
		if ("jwt".equals(proofType)) {
			// Check if we have multiple proof JWTs (proof_jwts array)
			JsonObject proofJwtsWrapper = env.getObject("proof_jwts");
			if (proofJwtsWrapper != null && proofJwtsWrapper.has("items")) {
				JsonArray proofJwtsArray = proofJwtsWrapper.getAsJsonArray("items");
				for (JsonElement proofJwtEl : proofJwtsArray) {
					JsonObject proofJwt = proofJwtEl.getAsJsonObject();
					JsonElement publicJWK = proofJwt.has("header") ?
						proofJwt.getAsJsonObject("header").get("jwk") : null;
					if (publicJWK == null) {
						throw error("Couldn't find public JWK in proof_jwt header.jwk",
							args("proof_type", proofType, "proof_jwt", proofJwt));
					}
					publicJWKs.add(parseJwk(publicJWK));
				}
				log("Found " + publicJWKs.size() + " JWK(s) from jwt proofs",
					args("keys", publicJWKs));
			} else {
				// Fallback to single proof_jwt for backward compatibility
				JsonElement publicJWK = env.getElementFromObject("proof_jwt", "header.jwk");
				if (publicJWK == null) {
					throw error("Couldn't find public JWK in proof_jwt header.jwk for proof type: " + proofType,
						args("proof_type", proofType));
				}
				publicJWKs.add(parseJwk(publicJWK));
				log("Found JWK in jwt proof", args("keys", publicJWKs));
			}
		} else if ("attestation".equals(proofType)) {
			JsonElement proofAttestation = env.getElementFromObject("proof_attestation", "claims.attested_keys");
			if (proofAttestation == null || !proofAttestation.isJsonArray()) {
				throw error("Couldn't find attested_keys in proof_attestation claims for proof type: " + proofType,
					args("proof_type", proofType));
			}
			var jwksKeys = proofAttestation.getAsJsonArray();
			if (jwksKeys.isEmpty()) {
				throw error("attested_keys of Attestation must not be empty");
			}
			// Add all keys from attested_keys - per spec we should issue a credential for each
			for (JsonElement key : jwksKeys) {
				publicJWKs.add(parseJwk(key));
			}
			log("Found " + publicJWKs.size() + " JWK(s) in attested_keys",
				args("keys", publicJWKs));
		} else {
			throw error("Cannot determine JWK from unsupported proof type: " + proofType, args("proof_type", proofType));
		}

		return publicJWKs;
	}

}
