# Modified version of standard httpd, which maps /static/ directly
# onto the source tree, which saves rebuilds when testing html/js
# tweaks, albeit it does mean you have to explicitly
# access https://localhost:8443/static/
# The only difference is apache config file used in the COPY line
FROM debian:buster
RUN apt-get update \
	&& apt-get install -y apache2 ssl-cert \
	&& apt-get clean
RUN \
	a2enmod headers proxy proxy_http rewrite ssl \
	&& a2dissite 000-default.conf
COPY ports.conf /etc/apache2/ports.conf
COPY server-static.conf /etc/apache2/sites-enabled
ENTRYPOINT ["apachectl", "-DFOREGROUND"]
