FROM openjdk:11-jdk-slim
COPY fapi-test-suite.jar /server/
ENV BASE_URL https://localhost:8443
ENV BASE_MTLS_URL https://localhost:8443
ENV MONGODB_HOST mongodb
EXPOSE 8080
ENTRYPOINT java \
  -D"fintechlabs.base_url=${BASE_URL}" \
  -D"fintechlabs.base_mtls_url=${BASE_MTLS_URL}" \
  -D"spring.data.mongodb.uri=mongodb://${MONGODB_HOST}:27017/test_suite" \
  -jar /server/fapi-test-suite.jar \
  -Djdk.tls.maxHandshakeMessageSize=65536
