package net.openid.conformance.authzen.interop.search.action;

import net.openid.conformance.plan.PublishTestPlan;
import net.openid.conformance.plan.TestPlan;

@PublishTestPlan(
	testPlanName = "authzen-pdp-interop-action-search-test-plan",
	displayName = "Authzen 1.0: PDP Interop server test for Action Search - alpha tests (not currently part of certification program)",
	profile = TestPlan.ProfileNames.authzenTest,
	specFamily = TestPlan.SpecFamilyNames.authzen,
	testModules = {
		// Search Demo test cases
		// https://github.com/openid/authzen/blob/main/interop/authzen-search-demo/test/action/results.json
		AuthzenPDPInteropActionSearch01Test.class,
		AuthzenPDPInteropActionSearch02Test.class,
		AuthzenPDPInteropActionSearch03Test.class,
		AuthzenPDPInteropActionSearch04Test.class,
		AuthzenPDPInteropActionSearch05Test.class,
		AuthzenPDPInteropActionSearch06Test.class,
		AuthzenPDPInteropActionSearch07Test.class,
		AuthzenPDPInteropActionSearch08Test.class,
		AuthzenPDPInteropActionSearch09Test.class,
		AuthzenPDPInteropActionSearch10Test.class,
		AuthzenPDPInteropActionSearch11Test.class,
		AuthzenPDPInteropActionSearch12Test.class,
		AuthzenPDPInteropActionSearch13Test.class,
		AuthzenPDPInteropActionSearch14Test.class,
		AuthzenPDPInteropActionSearch15Test.class,
		AuthzenPDPInteropActionSearch16Test.class,
		AuthzenPDPInteropActionSearch17Test.class,
		AuthzenPDPInteropActionSearch18Test.class,
		AuthzenPDPInteropActionSearch19Test.class,
		AuthzenPDPInteropActionSearch20Test.class,

		AuthzenPDPInteropActionSearch21Test.class,
		AuthzenPDPInteropActionSearch22Test.class,
		AuthzenPDPInteropActionSearch23Test.class,
		AuthzenPDPInteropActionSearch24Test.class,
		AuthzenPDPInteropActionSearch25Test.class,
		AuthzenPDPInteropActionSearch26Test.class,
		AuthzenPDPInteropActionSearch27Test.class,
		AuthzenPDPInteropActionSearch28Test.class,
		AuthzenPDPInteropActionSearch29Test.class,
		AuthzenPDPInteropActionSearch30Test.class,

		AuthzenPDPInteropActionSearch31Test.class,
		AuthzenPDPInteropActionSearch32Test.class,
		AuthzenPDPInteropActionSearch33Test.class,
		AuthzenPDPInteropActionSearch34Test.class,
		AuthzenPDPInteropActionSearch35Test.class,
		AuthzenPDPInteropActionSearch36Test.class,
		AuthzenPDPInteropActionSearch37Test.class,
		AuthzenPDPInteropActionSearch38Test.class,
		AuthzenPDPInteropActionSearch39Test.class,
		AuthzenPDPInteropActionSearch40Test.class,

		AuthzenPDPInteropActionSearch41Test.class,
		AuthzenPDPInteropActionSearch42Test.class,
		AuthzenPDPInteropActionSearch43Test.class,
		AuthzenPDPInteropActionSearch44Test.class,
		AuthzenPDPInteropActionSearch45Test.class,
		AuthzenPDPInteropActionSearch46Test.class,
		AuthzenPDPInteropActionSearch47Test.class,
		AuthzenPDPInteropActionSearch48Test.class,
		AuthzenPDPInteropActionSearch49Test.class,
		AuthzenPDPInteropActionSearch50Test.class,

		AuthzenPDPInteropActionSearch51Test.class,
		AuthzenPDPInteropActionSearch52Test.class,
		AuthzenPDPInteropActionSearch53Test.class,
		AuthzenPDPInteropActionSearch54Test.class,
		AuthzenPDPInteropActionSearch55Test.class,
		AuthzenPDPInteropActionSearch56Test.class,
		AuthzenPDPInteropActionSearch57Test.class,
		AuthzenPDPInteropActionSearch58Test.class,
		AuthzenPDPInteropActionSearch59Test.class,
		AuthzenPDPInteropActionSearch60Test.class,

		AuthzenPDPInteropActionSearch61Test.class,
		AuthzenPDPInteropActionSearch62Test.class,
		AuthzenPDPInteropActionSearch63Test.class,
		AuthzenPDPInteropActionSearch64Test.class,
		AuthzenPDPInteropActionSearch65Test.class,
		AuthzenPDPInteropActionSearch66Test.class,
		AuthzenPDPInteropActionSearch67Test.class,
		AuthzenPDPInteropActionSearch68Test.class,
		AuthzenPDPInteropActionSearch69Test.class,
		AuthzenPDPInteropActionSearch70Test.class,

		AuthzenPDPInteropActionSearch71Test.class,
		AuthzenPDPInteropActionSearch72Test.class,
		AuthzenPDPInteropActionSearch73Test.class,
		AuthzenPDPInteropActionSearch74Test.class,
		AuthzenPDPInteropActionSearch75Test.class,
		AuthzenPDPInteropActionSearch76Test.class,
		AuthzenPDPInteropActionSearch77Test.class,
		AuthzenPDPInteropActionSearch78Test.class,
		AuthzenPDPInteropActionSearch79Test.class,
		AuthzenPDPInteropActionSearch80Test.class,

		AuthzenPDPInteropActionSearch81Test.class,
		AuthzenPDPInteropActionSearch82Test.class,
		AuthzenPDPInteropActionSearch83Test.class,
		AuthzenPDPInteropActionSearch84Test.class,
		AuthzenPDPInteropActionSearch85Test.class,
		AuthzenPDPInteropActionSearch86Test.class,
		AuthzenPDPInteropActionSearch87Test.class,
		AuthzenPDPInteropActionSearch88Test.class,
		AuthzenPDPInteropActionSearch89Test.class,
		AuthzenPDPInteropActionSearch90Test.class,

		AuthzenPDPInteropActionSearch91Test.class,
		AuthzenPDPInteropActionSearch92Test.class,
		AuthzenPDPInteropActionSearch93Test.class,
		AuthzenPDPInteropActionSearch94Test.class,
		AuthzenPDPInteropActionSearch95Test.class,
		AuthzenPDPInteropActionSearch96Test.class,
		AuthzenPDPInteropActionSearch97Test.class,
		AuthzenPDPInteropActionSearch98Test.class,
		AuthzenPDPInteropActionSearch99Test.class,
		AuthzenPDPInteropActionSearch100Test.class
	}
)
public class AuthzenPDPInteropActionSearchTestPlan implements TestPlan {
}
